### ISSUE TITLE
MarqoVectorStoreDriver.query vector

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#100]
Currently, `MarqoVectorStoreDriver.query` always returns an empty list as a vector value. That behavior should be conditional based on the value of `include_vectors`. @RaynorChavez, how hard would it be to add that functionality?

**Comment by RaynorChavez** [comment]
Hi @vasinov, thanks for bringing that up! Fixed it with PR: https://github.com/griptape-ai/griptape/pull/108

**Comment by vasinov** [comment]
Thanks!
