### ISSUE TITLE
Ollama embedding driver support

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#1005]
- [x ] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
There isn't a way currently to have an embedding driver running locally. Ollama has embedding models, but we don't have a way to access them.

**Describe the solution you'd like**
Like the OllamaPromptDriver, I'd like an OllamaEmbeddingDriver

**Comment by collindutter** [comment]
Hey @shhlife we've got an [Ollama Embedding Driver](https://docs.griptape.ai/latest/griptape-framework/drivers/embedding-drivers/#ollama) coming in the `0.29.0` release this week.
