### ISSUE TITLE
Auto Create Vector Store Resources

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#1030]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
When using Vector Store Drivers, users need to manually create the appropriate resources (indexes/collections/etc) before using the Driver. This can be time consuming and error prone.

**Describe the solution you'd like**
Griptape should have the option to automatically create these resources when first using the Vector Store Driver.

**Describe alternatives you've considered**
Call use the underlying SDK directly.

**Additional context**
https://github.com/griptape-ai/griptape/pull/1022#discussion_r1695524314

**Comment by michal-repo** [comment]
It was already implemented and removed https://github.com/griptape-ai/griptape/issues/607

**Comment by collindutter** [comment]
Great point, @michal-repo! I had completely forgotten that we intentionally decided to remove that functionality to reduce Griptape's maintenance surface area. Griptape's focus should remain solely on data-plane operations.
