### ISSUE TITLE
Rename `GenericArtifact` to `Artifact` and use as parent class for other `Artifact`s

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#1049]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by collindutter** [comment]
The reasoning against `Artifact` was that it was inconsistent with other naming patterns in the framework ([context here](https://github.com/griptape-ai/griptape/pull/983)). While this is mostly true, we've got an abstract `BaseStructureConfig` and a concrete `StructureConfig`. So we need to pick a direction and be consistent with it.

Separately, I'm not sure we should necessarily change the parent of other classes. `Artifact` may implement some unique logic in the future that we don't want applied to other Artifact types.

**Comment by collindutter** [comment]
After some discussion with @vasinov, we've decided to keep `GenericArtifact` and bring `ConversationMemory` and `StructureConfig` in-line with a similar naming convention.
