### ISSUE TITLE
ErrorArtifact in Conversation Memory Causes Subsequent Task Failures

### ISSUE THREAD

**Issue by nicholasks** [griptape-ai/griptape#1071]
- [X] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
When a task returns an `ErrorArtifact`, subsequent calls/tasks fail as the `__to_message_content` (/griptape/common/prompt_stack/prompt_stack.py) raise an exception.

If you have a conversation memory attached to an Agent and the API returns an error, the `ErrorArtifact` gets appended to the conversation history.

**To Reproduce**
You can trigger an error by setting an invalid API KEY:

```python
import os

from dotenv import load_dotenv


def ask(question: str):
    from griptape.drivers import LocalConversationMemoryDriver
    from griptape.memory.structure import ConversationMemory
    from griptape.structures import Agent

    local_driver = LocalConversationMemoryDriver(file_path="memory.json")
    agent = Agent(conversation_memory=ConversationMemory(driver=local_driver))
    agent.run(question)


if __name__ == "__main__":
    load_dotenv()
    DEFAULT_KEY = os.environ.get("OPENAI_API_KEY", "MISSING KEY")
    INVALID_KEY = "sk-invalid-key-test"

    ask("Surfing is my favorite sport.")

    os.environ["OPENAI_API_KEY"] = INVALID_KEY
    ask("I like horses.")

    os.environ["OPENAI_API_KEY"] = DEFAULT_KEY

    # Subsequent calls will fail, as the memory has an ErrorArtifact
    ask("What is my favorite sport and animal?")

```

**Expected behavior**
Subsequent calls should not fail if you have a failed run on your conversation history (memory).

**Screenshots**
![Screenshot from 2024-08-16 16-06-07](https://github.com/user-attachments/assets/1df2d286-776e-40c3-a02d-88483ada039e)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04.4 LTS
 - Griptape version: 0.29.1

**Additional context**
It used to work fine on Griptape version 0.27.2, after updating to the last version it seems `Artifacts` were introduced in the memory instead of simple input/output strings.

**Comment by collindutter** [comment]
Thanks for the issue report and reproduction example @nicholasks! I am able to reproduce, will work on a fix shortly.
