### ISSUE TITLE
As part of a minor version bump, for example 0.29.1 to 0.30.1, add a deprecation warning decorator

### ISSUE THREAD

**Issue by jm-nab** [griptape-ai/griptape#1106]
It was very confusing to find out a few of the tools had been refactored and renamed:

- RagClient / RagTool
- StructuredRunClient / StructureRunTool
- Calculator / CalculatorTool
- DateTime / DateTimeTool
-  Workflow.__init__() got an unexpected keyword argument 'config'

As part of any upcoming releases would it be possible to add a `@deprecation("0.31.1 renamed to ...")` decorator specifying that the naming will be updated/changed

- https://peps.python.org/pep-0702/#example
- https://github.com/tantale/deprecated

**Comment by collindutter** [comment]
Hi @jm-nab, apologies for the confusion that came from the breaking changes in this last release.

Large breaking changes such as this should decrease as we get closer to a 1.0 release. Post 1.0, any breaking changes will absolutely handled gradually with deprecation decorators as you suggested. While we're pre-1.0, perhaps a detailed migration guide on each release would help?

**Comment by jm-nab** [comment]
@collindutter ah okay, makes sense. Is there a migration guide? I looked around but haven't found it.

**Comment by collindutter** [comment]
Not today, but we can start one going forward! Right now the best source of truth is the [changelog](https://github.com/griptape-ai/griptape/blob/e18db160b54e3ec0d95a817235ed804c908f4eb9/CHANGELOG.md#L55-L57) which unfortunately did not describe this Tool rename in much detail.

Thanks for your patience, we'll improve this process 🙂

**Comment by jm-nab** [comment]
@collindutter Thank you 🙏

**Comment by collindutter** [comment]
@jm-nab I'm going to close this ticket with the outcome that we'll add a "Migration Guide" section to our docs. I'll make sure to call it out here once it exists.

Apologies again for the frustrating migration, it'll be smoother going forward. Feel free to reach out on Discord/Github issues if you have any questions/concerns with specific migration items.

**Comment by jm-nab** [comment]
@collindutter btw, Thank you!

- https://github.com/griptape-ai/griptape/blob/4ff7fce0958e4f8734659902a21b216348ea3f1e/MIGRATION.md?plain=1#L1

Especially with the major version release:

- https://github.com/griptape-ai/griptape/blob/36d5d2c0c22ffabc85b7e017952582905ee94554/CHANGELOG.md#100---2024-12-09
