### ISSUE TITLE
Agent is unable to retain its memory using ConversationMemory() 

### ISSUE THREAD

**Issue by jin167** [griptape-ai/griptape#111]
**Describe the bug**
Agent is unable to retain its memory if it's provided with tools.

**To Reproduce**
1. Run the example code below

```
from griptape.memory.tool import TextToolMemory, BlobToolMemory
from griptape.tools import Calculator, WebScraper, FileManager, TextMemoryBrowser
from griptape.structures import Agent
from griptape.utils import Chat
from griptape.rules import Rule, Ruleset
from griptape.memory.structure import ConversationMemory, BufferConversationMemory

"""
Define tool memory for storing textual and
non-textual content.
"""
text_memory = TextToolMemory()
blob_memory = BlobToolMemory()

"""
WebScraper enables LLMs to web pages.

Here we wrap WebScraper's `get_content` activity
in the text memory. Any result from this
activity will be stored in that memory and the result
ID will be returned to the LLM.
"""
web_scraper = WebScraper(
    output_memory={
        "get_content": [text_memory]
    }
)

"""
FileManager enables LLMs to store and load files from disk.

Here we set input_memory for tool activities to pull data from and
wrap the `load_files_from_disk` activity output with the blob memory.
"""
file_manager = FileManager(
    input_memory=[text_memory],
    output_memory={
        "load_files_from_disk": [blob_memory]
    }
)

"""
TextMemoryBrowser enables LLMs to browse, extract, and query text memory.
"""
memory_browser = TextMemoryBrowser(
    input_memory=[text_memory]
)

agent = Agent(
    memory=ConversationMemory(),
    tools=[web_scraper, file_manager, memory_browser],
)

Chat(agent).start()
```

2. Ask a question (e.g., where is new york)

3. Ask the agent to answer your previous question.

**Expected behavior**
Agent has memory of the previous conversation.

**Screenshots**
![image](https://github.com/griptape-ai/griptape/assets/50513176/068cfc7a-d663-4932-81fb-a8d489cbf8e2)

**Comment by kyleroche** [comment]
Interesting. Thanks for posting this. There seems to be a bug w/ conversational memory. That example was demonstrating something different but seems to have caused it. We'll track it down. 

For basic conversational memory, you can just use the following code: 

`
from griptape.structures import Agent
from griptape.utils import Chat

agent = Agent()

Chat(agent).start()
`

**That'll keep track of a basic conversation.** 

`Q: my name is kyle 
processing...
[07/17/23 22:08:03] INFO     Task ac950f6942494f309900eea138cbd0e5              
                             Input: my name is kyle                             
                    INFO     Task ac950f6942494f309900eea138cbd0e5              
                             Output: Nice to meet you, Kyle! How can I assist   
                             you today?                                         
A: Nice to meet you, Kyle! How can I assist you today?
Q: what's my name 
processing...
[07/17/23 22:08:07] INFO     Task ac950f6942494f309900eea138cbd0e5              
                             Input: what's my name                              
[07/17/23 22:08:08] INFO     Task ac950f6942494f309900eea138cbd0e5              
                             Output: Your name is Kyle. How can I assist you    
                             today, Kyle?                                       
A: Your name is Kyle. How can I assist you today, Kyle?
Q: `

**Comment by jin167** [comment]
Thank you, Kyle.

Yeah, seems to happen only if you add tools to the agent and similar problem occurs with the pipeline as well.

**Comment by vasinov** [comment]
@jin167, thanks for reporting the issue! The latest version of Griptape (0.14.0) has several base prompt tweaks that fix this issue. Let us know if it happens again.
