### ISSUE TITLE
prompt_task.py prompt_stack should check weather self.structure is None

### ISSUE THREAD

**Issue by Chuan-Zh** [griptape-ai/griptape#1155]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
If use prompt_task without a structure, access to self.structure might raise None exception.

**To Reproduce**
A minimal, reproducible code example.
``` python
text_artifact = TextArtifact(
    "Respond to the user's following question 'who are you' in the language '{{preferred_language}}' and tone '{{tone}}'."
)

prompt_task = PromptTask(
    text_artifact,
    context={"preferred_language": "ENGLISH", "tone": "PLAYFUL"},
)

print(prompt_task.prompt_stack.to_json())
```

**Comment by collindutter** [comment]
Thanks for the issue @Chuan-Zh! Would an improved exception be sufficient for your use-case, or are you looking to use Tasks without a Structure?

**Comment by Chuan-Zh** [comment]
An improved exception is ok.

> Thanks for the issue @Chuan-Zh! Would an improved exception be sufficient for your use-case, or are you looking to use Tasks without a Structure?
