### ISSUE TITLE
Tavily support

### ISSUE THREAD

**Issue by konradre** [griptape-ai/griptape#1167]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

Tavily for websearch is a popular feature of many open-source repos.

They have a robust rate limited free tier search better than duckduckgo, though like Google it does require an api key (but its easier to get than Google's). 

Would be nice to see it available in Griptape.

**Comment by collindutter** [comment]
Thanks for the issue, @konradre! Tavily looks like a great service, I think it'd be an excellent Web Search Driver option.
