### ISSUE TITLE
Making parameter modifications on global Defaults drivers is ignored by the driver client.

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#1174]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
Any parameters set after init any drivers that use a client are ignored because the client is initialized during driver initialization

**To Reproduce**
```
Defaults.drivers_config = AzureOpenAiDriversConfig(
    azure_ad_token_provider=get_token,
    azure_endpoint=os.environ["AZURE_OPENAI_DEFAULT_ENDPOINT"],
)

Defaults.drivers_config.text_to_speech_driver.azure_endpoint = os.environ[
    "AZURE_OPENAI_OTHER_ENDPOINT"
]
```
the above fails at runtime because the client used for the `AzureOpenAiTextToSpeechDriver` does not have the updated endpoint set on the global config.

**Expected behavior**
The above config should set the correct endpoint for the client on the driver

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 0.5.1]

**Additional context**

**Comment by collindutter** [comment]
@vachillo was this fixed with #1173?
