### ISSUE TITLE
RateLimitError when reproducing simple Pipeline example

### ISSUE THREAD

**Issue by joelwiesmann** [griptape-ai/griptape#122]
**Describe the bug**
When I try to reproduce the pirate-pipeline example (https://docs.griptape.ai/en/latest/griptape-framework/structures/pipelines/) only the first task in the pipeline is executed successfully, for the 2nd it returns a ratelimit error.

**To Reproduce**
1. Go to https://docs.griptape.ai/en/latest/griptape-framework/structures/pipelines/
2. Copy & paste pirate-talk example
3. Run example
4. First task is executed, for the 2nd task an error is received:
```
attempt #1; slept for 0.0; last result: failed (RateLimitError Rate limit reached for 10KTPM-200RPM in organization xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.)
```

**Comment by collindutter** [comment]
@joelwiesmann can you please try changing your [prompt driver](https://docs.griptape.ai/en/latest/griptape-framework/structures/prompt-drivers/) to `gpt-3.5-turbo` or `gpt-3.5-turbo-16k`? The rate limits are much lower on `gpt-4`. Even so, it seems odd that griptape would be bumping into the limits out of box.

@vasinov thoughts? I've noticed this behavior on my own API key.

**Comment by vasinov** [comment]
@joelwiesmann, thanks for reporting the issue! Are you the only one using the API in your org? Does OpenAI return the rate limit error on the first pipeline run? I hooked up the token count utility to that example and it shows that it only used `467` tokens:

```python
from griptape import utils
from griptape.events import StartPromptEvent, FinishPromptEvent
from griptape.memory.structure import ConversationMemory
from griptape.tasks import PromptTask
from griptape.structures import Pipeline

token_counter = utils.TokenCounter()

pipeline = Pipeline(
    memory=ConversationMemory(),
    event_listeners={
        StartPromptEvent: [
            lambda e: token_counter.add_tokens(e.token_count)
        ],
        FinishPromptEvent: [
            lambda e: token_counter.add_tokens(e.token_count)
        ],
    }

)

pipeline.add_tasks(
    # take the first argument from the pipeline `run` method
    PromptTask("{{ args[0] }}"),
    # take the input from the previous task and insert it into the prompt
    PromptTask("Say the following like a pirate: {{ input }}")
)

pipeline.run("I am Scotty, who are you?")
pipeline.run("Who am I?")

print(f"total tokens: {token_counter.tokens}")
```

Could you please run it to confirm that it's using the same number of tokens for you? Thanks!

**Comment by joelwiesmann** [comment]
Hi @vasinov

I'm the only user in my organisation.
The token token count was: 2935 🤷

I have an error message regarding an incompatible version of pyarrow (UserWarning: You have an incompatible version of 'pyarrow' installed (12.0.1), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'). I resolved this but it did not fix the issue.

@collindutter 
**Works** with gpt-3.5-turbo => 372 tokens
**Works** with gpt-3.5-turbo-16k => 372 tokens

As per https://docs.griptape.ai/en/latest/griptape-framework/structures/prompt-drivers/ the default model should be gpt-3.5-turbo but I think this is not accurate anymore (seems to be gpt-4 right now).

**Comment by joelwiesmann** [comment]
@vasinov I might need to add, that it was running for quiet some time. The retry message was counting up to 36 seconds wait time before the result arrived. I don't know if the events fire with every attempt.

WARNING:root:<RetryCallState 1832810232896: attempt #1; slept for 0.0; last result: failed (RateLimitError Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.)>

**Comment by vasinov** [comment]
@joelwiesmann, it appears that OpenAI APIs can quantize rate limiting [1]:

> Rate limits can be quantized, meaning they are enforced over shorter periods of time (e.g. 60,000 requests/minute may be enforced as 1,000 requests/second).

The imprecise language (e.g., "can be," "may be") is concerning. They also imply that this is only applies to RPM. In my tests with an org that has a GPT-4 10k TPM limit, it's evident that prompts greater than ~2k input tokens (and maxed out output tokens) get rate limited. This, in effect, prevents accounts with lower TPM limits to take full advantage of prompt limits.

AS a temporary measure, I added a `max_tokens` parameter to the `OpenAiPromptDriver`. After upgrading `griptape`, you should be able to run the pipelines examples with GPT-4 like this:

```python
Pipeline(
    prompt_driver=OpenAiPromptDriver(
        model="gpt-4",
        max_tokens=200 # can likely be much higher
    )
)
```

Let me know if that helps!

1. https://help.openai.com/en/articles/6891753-rate-limit-advice

**Comment by vasinov** [comment]
> The token token count was: 2935

The reason your count was so high is because the token counter counts all tokens including the ones rejected by the API.

**Comment by joelwiesmann** [comment]
Hello @vasinov 

The max_token parameter did the job :-D!

If I understood the problem correctly:
If my request contains 500 tokens and my max_tokens setting is 1'000, the TPM limit calculation would be done with 1'500 tokens. This means that if I send a few requests, I would exceed the limit even if I didn't have that many tokens in my request/responses?

Regards & thanks for the quick solution
Joel
