### ISSUE TITLE
Pylint GitHub Action

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#124]
Griptape developers want the [Pylint](https://github.com/pylint-dev/pylint) GitHub action to automatically enforce coding standards for [griptape](https://github.com/griptape-ai/griptape/) and [griptape-tools](https://github.com/griptape-ai/griptape/).

**Comment by collindutter** [comment]
Action should now use `ruff` instead based on [this PR](https://github.com/griptape-ai/griptape/pull/221).

**Comment by collindutter** [comment]
`black` Github Action added in #143
