### ISSUE TITLE
Support local .env file in multi_agent_workflow_1 sample

### ISSUE THREAD

**Issue by victorgarciaaprea** [griptape-ai/griptape#1281]
- [X] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
The sample uses several secrets (e.g. Goole API key) and expects them to be stored in environment variables but there is no support for a local .env file.

**Describe the solution you'd like**
During local development I would like to store they keys in the .env file and have the sample use that.

**Describe alternatives you've considered**
Editing the system environment variables in a specific way for whatever operating system you are running.

**Additional context**
None.

**Comment by collindutter** [comment]
Hey @victorgarciaaprea, thanks for trying out Griptape! We'd like to avoid making any assumptions about how the user's environment variables are loaded in the griptape docs. For instance, using something like [direnv](https://direnv.net/) is a popular alternative to using python-dotenv. Griptape Tradeschool, by contrast, is a bit more opinionated and walks through the process of [setting up](https://learn.griptape.ai/latest/setup/02_openai/#installing-python-dotenv) your local environment variables.

The change you've proposed in [your PR](https://github.com/griptape-ai/griptape/pulls) is a great solution but I don't think we're looking to integrate it at this time.
