### ISSUE TITLE
Drivers unit tests

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#130]
Multiple drivers are missing proper unit tests. We should add more unit tests with third-party APIs properly mocked.

**Comment by dylanholmes** [comment]
@vasinov I did start on improving the vector store unit tests as well, though I've only partially finished one of the vector store drivers.

Seeing that I was planning on working on something related to griptape tomorrow morning for a bit, is there another issue that you'd like to see get done? (If not, I'll just finish the vector store unit tests like I had planned)
