### ISSUE TITLE
Add Bria.ai image generation driver

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#1320]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
Bria.ai offers 100% fully-licensed datasets for image generation. It would be very helpful to have a Bria.ai driver as part of the framework so customers can take advantage of this and create images they can use commercially.

**Describe the solution you'd like**
A `BriaImageGenerationDriver` for image generation, image editing, and more. They have a few apis available - including the ability to train a model. They also provide attribution so artists whose work contributes to image generation get paid.

**Comment by collindutter** [comment]
I've partially implemented this as a [griptape extension](https://github.com/griptape-ai/griptape-bria). Image Variation is not implemented since it requires passing the image as a URL which is not currently supported by Griptape.

**Comment by collindutter** [comment]
Going to close this for now since we've got a rough version working. Any future enhancements/fixes issues can be made on the Bria repo.
