### ISSUE TITLE
Add a BlackForest Flux ImageDriver

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#1323]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
BlackForest has a great image generator using Flux. They have an API available (https://docs.bfl.ml/) and having a driver for image generation would be very useful.

**Comment by collindutter** [comment]
@shhlife I've implemented this as an [extension](https://github.com/griptape-ai/griptape-black-forest) for now. We can evaluate merging upstream in the future.
