### ISSUE TITLE
AmazonBedrockPromptDriver fails with default max_tokens

### ISSUE THREAD

**Issue by TheRyanBurke** [griptape-ai/griptape#1410]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
When using the AmazonBedrockPromptDriver, the request to bedrock:InvokeModel fails because the default value of None is passed to inferenceConfig.maxTokens and boto3 expects this to be an int if provided. 

Error: `WARNING:root:<RetryCallState 126251629424576: attempt #1; slept for 0.0; last result: failed (ParamValidationError Parameter validation failed:
Invalid type for parameter inferenceConfig.maxTokens, value: None, type: <class 'NoneType'>, valid types: <class 'int'>)>` 

**To Reproduce**

```
import boto3

from griptape.drivers import AmazonBedrockPromptDriver
from griptape.structures import Agent

prompt_driver: AmazonBedrockPromptDriver = AmazonBedrockPromptDriver(
        model="us.amazon.nova-micro-v1:0",
        session=boto3.Session(
            profile_name=os.getenv("AWS_PROFILE"),
            region_name=os.getenv("AWS_REGION")
        )
    )

agent: Agent = Agent(prompt_driver=prompt_driver)

agent.run("Give me a haiku about Android Netrunner")
```

**Expected behavior**
Amazon Bedrock is invoked and a haiku is generated in response.

Also expect this path to fail with an error, not throw a warning and continue trying with backoff. Note the log above is log level WARNING and it enters RetryCallState. No retry will ever change the state of the incorrect parameter and so this should fail out. 

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version: Server 24.10

**Additional context**
[Bedrock API reference](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InferenceConfiguration.html#API_runtime_InferenceConfiguration_Contents) defines inferenceConfig.maxTokens parameter as optional. 

Suggest the Bedrock driver source [inferenceConfig.maxTokens](https://github.com/griptape-ai/griptape/blob/dev/griptape/drivers/prompt/amazon_bedrock_prompt_driver.py#L115) from the tokenizer's _default_max_output_tokens or to have the driver set self.maxTokens to the tokenizer's _default_max_output_tokens when maxTokens is not defined in instantiation. Problem seems to stem from the fact that self.maxTokens never gets a value other than None unless I set it manually during instantiation of the driver. Not sure why inference.maxTokens is getting a value of None when the [unpack ](https://github.com/griptape-ai/griptape/blob/3606156d27567a261562a2d9ed6ca68fca049a98/griptape/drivers/prompt/amazon_bedrock_prompt_driver.py#L115) should result in _no_ maxTokens attribute being present at all.

I can see a warning during instantiation that my Bedrock model is not found and a default max output tokens is set to 1000: `WARNING:root:Model us.amazon.nova-micro-v1:0 not found in MODEL_PREFIXES_TO_MAX_OUTPUT_TOKENS, using default value of 1000.` It is not clear why there was no contingency in this code path to set the driver's maxTokens since maxTokens is the attribute sourced for the boto3 request. Perhaps this was overlooked.

**Comment by TheRyanBurke** [comment]
My workaround is to set the max_tokens property during driver instantiation using the tokenizer's default max output tokens:

```
prompt_driver: AmazonBedrockPromptDriver = AmazonBedrockPromptDriver(
        model=os.getenv("AWS_BEDROCK_MODEL"),
        session=boto3.Session(
            profile_name=os.getenv("AWS_PROFILE"),
            region_name=os.getenv("AWS_REGION")
        ),
        max_tokens=AmazonBedrockTokenizer(
            model=os.getenv("AWS_BEDROCK_MODEL")
        )._default_max_output_tokens()
    )
```

**Comment by collindutter** [comment]
Hey @TheRyanBurke, thanks for the detailed issue report! This is actually fixed on the dev branch via https://github.com/griptape-ai/griptape/pull/1328. And we're cutting a release today with https://github.com/griptape-ai/griptape/pull/1409.

Regarding the default max tokens warning, it is because we don't have an entry for `us.amazon` [here](https://github.com/griptape-ai/griptape/blob/16a98d709046994584d3e34d4bcd92a0336673d7/griptape/tokenizers/amazon_bedrock_tokenizer.py#L10-L34). Updating your model to `amazon.nova-micro-v1:0` will "fix" the warning, though admittedly this feels like a unsatisfactory workaround. I'd really much prefer to get out of the business of maintaining a map of models to token limits.

**Comment by collindutter** [comment]
@TheRyanBurke I'm going to close this since #1409 has been merged. Please feel free to re-open if you feel something is still missing!
