### ISSUE TITLE
Add bucket CRUD functionality to GriptapeCloudFileManagerDriver

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#1430]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

It would be very helpful to be able to create, rename, update, and delete buckets with the CriptapeCloudFileManagerDriver.

**Comment by collindutter** [comment]
It was agreed upon offline that Griptape should not play the role of creating infrastructure as it greatly increases our maintenance surface area.  CRUD operations are better suited for that platform's SDK.

More context [here](https://github.com/griptape-ai/griptape/issues/607#issuecomment-1906456180).
