### ISSUE TITLE
[Docs] Sample code on file-manager-tool docs page is incorrect 

### ISSUE THREAD

**Issue by ian-griptape-ai** [griptape-ai/griptape#1445]
☑️ I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**

The sample code in docs/griptape-tools/official-tools/src/file_manager_tool_1.py is incorrect 

`Path(filename).write_text(filename)`

should read

`Path(filename).write_text(content)`

**Additional context**

Docs issue. Happy to fix myself if that is ok with you?

**Comment by collindutter** [comment]
Great catch! A PR would be great, would you mind updating with the newly added `TextLoader.save()`?

**Comment by ian-griptape-ai** [comment]
First day. Can you explain a little more?
