### ISSUE TITLE
Merge PromptTask, ToolkitTask, and ToolTask

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#1464]
- [x] I have read and agree to the [[contributing guidelines](https://github.com/griptape-ai/griptape#contributing)](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
  
Users find it unclear when to use each of the three types of Prompt Tasks. For example, `ToolkitTask` can handle everything that `PromptTask` can, making it difficult to justify when to use `PromptTask`. Additionally, `ToolTask` returns tool results directly to the user, while `ToolkitTask` does not, further adding to the confusion.

**Describe the solution you'd like**

Simplify the framework by merging all three task types into a single `PromptTask`. The `PromptTask` could include a configurable field to toggle between different tool-calling strategies, such as:

- **Direct Tool Results**: Tool results are returned directly to the user (current `ToolTask` behavior).  
- **LLM-Mediated Results**: Tool results are fed into the LLM until it generates a final response, which is then returned to the user (current `ToolkitTask` behavior).  
- **Combined Results**: Tool results are fed into the LLM until it generates a response, after which both the response and the tool results are returned to the user (currently unsupported).

**Describe alternatives you've considered**

One alternative is abstracting the logic into different types of Prompt Engines that users can swap between. However, this approach only adds to the complexity. 

Prompt Drivers are responsible for tools, it's reasonable to assume that Prompt Task can be too.

**Comment by emjay07** [comment]
The main thing I like `ToolTask` for is that it doesn't use conversation memory to try and derive when/what tool to use, it just uses the tool I give it. Will that functionality still exist with the Direct Tool Results?

**Comment by collindutter** [comment]
Very good to know! I think that could look something like:

```python
PromptTask(
   conversation_memory=None, # this is a newly added field
   tools=[Foo(), Bar()] # no longer restricted to just one tool,
   tool_use_strategy="any" # return the tool results directly
)
```

**Comment by emjay07** [comment]
That seems reasonable! With documentation/examples on how to tune some of these parameters to get the expected results, seems like a much simpler way!
