### ISSUE TITLE
`MongoDbAtlasVectorStoreDriver` should support vector querying

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#150]
Currently, `MongoDbAtlasVectorStoreDriver` doesn't support querying. We can use [the `knnBeta` operator](https://www.mongodb.com/docs/atlas/atlas-search/knn-beta/) in Atlas Search to achieve that.

**Comment by trish11953** [comment]
Done!

**Comment by vasinov** [comment]
https://github.com/griptape-ai/griptape/pull/151
