### ISSUE TITLE
Update Anthropic Client

### ISSUE THREAD

**Issue by krrishdholakia** [griptape-ai/griptape#153]
Anthropic changed their python sdk - making this code line outdated.

https://github.com/griptape-ai/griptape/blob/18d2b9486b28c98ce17cce17338a9626cba901c4/griptape/drivers/prompt/anthropic_prompt_driver.py#L25

Would love to know if this might help - https://github.com/BerriAI/litellm

~100 lines of code, that standardizes all the llm api calls to the OpenAI call
```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["ANTHROPIC_API_KEY"] = "anthropic key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# anthropic call
response = completion("claude-v-2", messages)
```

**Comment by krrishdholakia** [comment]
cc: @vasinov @collindutter

**Comment by collindutter** [comment]
Thanks for the report @krrishdholakia! Seems like this came from their [0.3.0](https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.3.0) release. Though griptape's anthropic sdk should be version locked at [0.2.10](https://github.com/griptape-ai/griptape/blob/main/poetry.lock#L138), are you finding this is not the case when using?

And thank you for the suggestion on litellm, we will check it out!

**Comment by vasinov** [comment]
@krrishdholakia, thanks! Will update anthropic dependency as part of https://github.com/griptape-ai/griptape/pull/149
