### ISSUE TITLE
Custom prompt template support for different languages

### ISSUE THREAD

**Issue by joelwiesmann** [griptape-ai/griptape#156]
**Is your feature request related to a problem? Please describe.**
I can have a German conversation, but in some cases my response is in english.

Q: Was gibt 25*25?
A: Das Ergebnis von 25*25 ist 625.
Q: Wieso?
A: I don't know.

This is likely to be based on griptape/templates/prompts/tasks/toolkit/base.j2 which states to answer "I don't know." if the question can not be answered.

**Describe the solution you'd like**
The template is digged into some method calls and can not be overridden (easily). So I would propose a class attribute for griptape.utils.J2 to specify custom prompt directory path. It might still fallback to default prompt directory path if template is not available. Alternatively, there might be a griptape-languages module that can be maintained separately from the griptape "core" module which provides "language packs".

**Describe alternatives you've considered**
I tried to manipulate the prompt to have the LLM always respond in the language the question was asked in. This seems to work in most cases.

**Comment by vasinov** [comment]
@joelwiesmann, you can [add a `Ruleset`](https://docs.griptape.ai/en/latest/griptape-framework/structures/rulesets/) describing what format/language you want the LLM output to be in. Let me know if that does it for you.

Today, it's pretty difficult to override Griptape prompts as they consist of many dynamic parts that are assembled at runtime. There is an [ongoing PR](https://github.com/griptape-ai/griptape/pull/149) that addresses this issue. We are planning on finishing it in the next two weeks.
