### ISSUE TITLE
SQLAlchemy 2.0 not supported

### ISSUE THREAD

**Issue by iloveitaly** [griptape-ai/griptape#162]
**Describe the bug**
Getting this error from poetry when attempting to add griptape to an existing sqlalchemy project

```
Using version ^0.14.7 for griptape
Using version ^0.16.3 for griptape-tools

Updating dependencies
Resolving dependencies... (0.3s)

Because griptape (0.14.7) depends on sqlalchemy (>=1.0,<2.0)
 and no versions of griptape match >0.14.7,<0.15.0, griptape (>=0.14.7,<0.15.0) requires sqlalchemy (>=1.0,<2.0).
So, because good-ads depends on both sqlalchemy (^2.0.19) and griptape (^0.14.7), version solving failed.
```

**To Reproduce**
```
poetry add griptape griptape-tools
```

**Expected behavior**
Install griptape

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 13.3.1

**Additional context**

**Comment by vasinov** [comment]
@iloveitaly, hey Mike! 😄

We are currently relying on some `sqlalchemy 1.x`-specific functionality but we should definitely upgrade to `2.x`. Thanks for bringing this up!

**Comment by mattgiles** [comment]
This is an obstacle to adoption for me.

Curious what 1.x functionality is being relied upon / if you would accept a pull request for this work.

**Comment by vasinov** [comment]
@mattgiles, `1.x` is used in a handful of classes but the most significant blocker is in `SqlDriver.get_table_schema()`. Not a terribly hard migration but we just haven't gotten to it yet. If you'd like to submit a PR it would be most appreciated. Thanks!

**Comment by mattgiles** [comment]
@vasinov looks totally doable. I started down the path, but believe this issue is blocked by snowflake-sqlalchemry [here](https://github.com/snowflakedb/snowflake-sqlalchemy/issues/452). Hopefully they can figure that out.

**Comment by vasinov** [comment]
@mattgiles, ah, yes. that's another blocker that I forgot about.

**Comment by collindutter** [comment]
https://github.com/snowflakedb/snowflake-sqlalchemy/pull/469 was finally merged, hopefully they make a release soon.
