### ISSUE TITLE
ImportError: cannot import name 'TopologicalSorter' from 'graphlib'

### ISSUE THREAD

**Issue by alexanderwilkie** [griptape-ai/griptape#165]
**Describe the bug**
When I install Griptape from pip on my MacOS Ventura (Version 13.3.1 (22E261)) I get the following when trying to run any simple examples:

ImportError: cannot import name 'TopologicalSorter' from 'graphlib'

I can fix this by following https://stackoverflow.com/a/71119577. 

I'm confused why I don't see other people struggling with this one so please let me know if I've missed something obvious or it's already documented somewhere!

**Comment by shhlife** [comment]
Hi Alex,

i'm also using Ventura and haven't been hitting that problem, so I'm guessing it's something with your particular environment.. let's see if we can figure it out. Are you installing using a virtual environment? Did you import graphlib previously?

cheers!
-Jason

**Comment by collindutter** [comment]
@alexanderwilkie I've actually run into this myself when installing in a docker environment. The link you shared is the correct solution as of now.

@vasinov should `graphlib` be listed a [dependency](https://github.com/griptape-ai/griptape/blob/main/pyproject.toml#L24C10-L24C10) at all? It's a [built in module ](https://docs.python.org/3.9/library/graphlib.html)in python 3.9. And the [graphlib on pypi](https://pypi.org/project/graphlib/) doesn't appear to be maintained.

**Comment by vasinov** [comment]
@collindutter, you are right—it shouldn't be a dependency, since we support Python >=3.9.
