### ISSUE TITLE
Count Tokens example in the documentation no longer works

### ISSUE THREAD

**Issue by mgcollie** [griptape-ai/griptape#199]
**Describe the bug**
This page in the docs https://docs.griptape.ai/examples/count-tokens/ demonstrates how users can use the TokenCounter utility for keeping track of how many tokens have been used.

**To Reproduce**
1. Copy the code in the above page into a new file
2. run the code
3. see that `total tokens: 0`
4. set a breakpoint at line 11 in `token_counter.py`
5. run the code again in debug mode
6. see that the breakpoint is never hit

**Expected behavior**
The expected behavior is that this function should be called and the `total tokens`  should be non zero.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: 19045
 - Griptape Version: 0.15.3
 - Python Version: 3.11.4

**Additional context**
[Discord Thread](https://discord.com/channels/1096466116672487547/1148922713994448956)

**Comment by mgcollie** [comment]
Also tested this on Ubuntu 22.04.2 LTS and  python 3.10.6 and can still reproduce the bug.

![image](https://github.com/griptape-ai/griptape/assets/7805464/723c0fc8-f3ba-4cb5-89a5-de1298f62d81)

**Comment by collindutter** [comment]
Hey @mgcollie! This was resolved in [149](https://github.com/griptape-ai/griptape/pull/190); we should have a release that contains this fix out soon.

**Comment by mgcollie** [comment]
Thanks @collindutter !

**Comment by collindutter** [comment]
@mgcollie this has been fixed in [v0.16.0 release](https://github.com/griptape-ai/griptape/releases/tag/v0.16.0). Thanks for the report 🙂
