### ISSUE TITLE
Add control parameters to TextSummaryTask 

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#203]
**Is your feature request related to a problem? Please describe.**
TextSummaryTask is a great way to quickly summarize input text without needing to use COT. At the moment there isn't much control provided to the developer on how the given text should be summarized.

**Describe the solution you'd like**

It would be great to have some additional parameters (names TBD) such as:
* length
* target audience
* format

This would let us summarize with a specifc length (3 sentences, 2 paragraphs, etc) or for an audience (child, executive summary) or in a format (bullet points, yaml, json) etc.

**Comment by collindutter** [comment]
Implemented in https://github.com/griptape-ai/griptape/issues/342
