### ISSUE TITLE
Can FileManager and other tools work with text passed to it

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#205]
**Is your feature request related to a problem? Please describe.**
Currently FileManager and other tools only handle text passed directly from Memory.

It would make them a lot easier to use if they could also work with text directly passed to them. 

**Describe the solution you'd like**
This would allow us to pass data directly to FileManager and it would save it to disk:

```
pipeline = Pipeline()

pipeline.addTasks(
  PromptTask("Create a haiku about bananas"),
  ToolkitTask("Save the haiku to bananas.txt: {{ parent_output }}", tools=[ FileManager() ])
)
```

**Comment by collindutter** [comment]
@shhlife this will be possible in the next release via https://github.com/griptape-ai/griptape/pull/207
