### ISSUE TITLE
Replace `Union[]` with `|`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#226]
Since we already support the [pipe syntax](https://peps.python.org/pep-0604/) for union types in tools, we should update the whole code base to do it.

This task requires:
1. Replacing `Union[]` with `|`.
2. Removing `typing.Union` imports.
3. Adding `from __future__ import annotations` to files that use `|`.

**Comment by The-Keeper** [comment]
Hello. I can work on this.

**Comment by The-Keeper** [comment]
@vasinov 
The relevant PR is here: https://github.com/griptape-ai/griptape/pull/235
