### ISSUE TITLE
Add persistence to `LocalVectorStoreDriver`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#241]
Many QA, extraction, and summarization use cases don't require a sophisticated vector store to function correctly. Today, `LocalVectorStoreDriver` works great for those use cases in the context of conversational "in the moment" workflows but lacks a way to persist embeddings on disk.

I propose adding an on-by-default setting for persisting and automatically loading `LocalVectorStoreDriver.entries` from the disk with an optional custom path to the file.

**Comment by derekpai** [comment]
#109
