### ISSUE TITLE
Guidance: how should AmazonBedrockPromptDriver and BedrockTitanPromptModelDriver used?

### ISSUE THREAD

**Issue by massi-ang** [griptape-ai/griptape#244]
I have the following scenario, where Bedrock is in a different account/region from the account I am launching griptape.

I then create a boto3 Session with the credentials and region to access the Bedrock API.

I then try to initialize the prompt driver in the following way:

```
titan = AmazonBedrockPromptDriver(session=session, 
    prompt_model_driver=BedrockTitanPromptModelDriver(), 
    model="amazon.titan-tg1-large")
```

this call succeeds, but the bedrock client used by the `prompt_model_driver` is not created using the `session` I passed, but by using the default boto3 session. This means that `invoke_model` fails since the client configuration is not the right one.

**Comment by collindutter** [comment]
Hey @massi-ang! In order to set a custom session with `amazon.titan-tg1-large`, you need to provide the `session` to the `AmazonBedrockTokenizer` as well. Here is an example:

```python
import boto3
from griptape.structures import Agent
from griptape.tasks import PromptTask
from griptape.drivers import AmazonBedrockPromptDriver
from griptape.tokenizers import AmazonBedrockTokenizer
from griptape.drivers import (
    BedrockTitanPromptModelDriver,
)

session = boto3.Session(region_name="...", profile_name="...")
anthropic_prompt_driver = AmazonBedrockPromptDriver(
    model="amazon.titan-tg1-large",
    prompt_model_driver=BedrockTitanPromptModelDriver(
        tokenizer=AmazonBedrockTokenizer(session=session),
        top_p=1,
    ),
    temperature=0,
    session=session,
)
agent = Agent(
    prompt_driver=anthropic_prompt_driver,
)
agent.add_task(
    PromptTask(
        "Write an informational article for children about how birds fly."
        "Compare how birds fly to how airplanes fly."
        'Make sure to use the word "Thrust" at least three times.'
    ),
)

agent.run()
```

**Comment by massi-ang** [comment]
Thanks Collin, 

while this works, it seems to be a lot of undifferentiated heavy lifting. The difference in the code needed when requiring a specific session (which is pretty common) vs when using the default session is huge. It also means that the user needs to know which prompt_model_driver class to pass and which tokenizer class to pass. Can this be simplified?

For example if using the default session requires just:

```
anthropic_prompt_driver = AmazonBedrockPromptDriver(
    model="amazon.titan-tg1-large",)
```

I would like that to use a specific session should be as simple as:

```
anthropic_prompt_driver = AmazonBedrockPromptDriver(
    model="amazon.titan-tg1-large",
    session=session,
)
```

**Comment by collindutter** [comment]
Good news! I was able to get the simplified version working in #264. With these changes, this will work:
```python
import boto3
from griptape.structures import Agent
from griptape.tasks import PromptTask
from griptape.drivers import AmazonBedrockPromptDriver
from griptape.drivers import (
    BedrockTitanPromptModelDriver,
)

session = boto3.Session(
    region_name="...", profile_name="..."
)
anthropic_prompt_driver = AmazonBedrockPromptDriver(
    model="amazon.titan-tg1-large",
    prompt_model_driver=BedrockTitanPromptModelDriver(),
    session=session,
)
agent = Agent(
    prompt_driver=anthropic_prompt_driver,
)
agent.add_task(
    PromptTask(
        "Write an informational article for children about how birds fly."
        "Compare how birds fly to how airplanes fly."
        'Make sure to use the word "Thrust" at least three times.'
    ),
)

agent.run()
```
