### ISSUE TITLE
Agents always require setting prompt_driver with very low max_tokens

### ISSUE THREAD

**Issue by nulldiver** [griptape-ai/griptape#255]
**Describe the bug**
Without setting an explicit prompt_driver with very low tokens per minute, nearly all requests immediately hit a rate limit of 1000 tokens / minute. This is with no other activity beyond a simple agent request occurring on the account.

With a prompt_driver set, with a low max_tokens, eg:

    prompt_driver=OpenAiChatPromptDriver(
        model="gpt-3.5-turbo",
        max_tokens=200
    )
    
Things work as expected. With a larger max_tokens (eg. the defaults set for the models in Griptape):

    prompt_driver=OpenAiChatPromptDriver(
        model="gpt-3.5-turbo",
        max_tokens=4096
    ),

I get:
InvalidRequestError This model's maximum context length is 4097 tokens. However, you requested 4208 tokens.

**To Reproduce**
This has been the only behavior that I have seen while using Griptape.
This is not a behavior that I have observed directly working with OpenAI's python APIs.

**Desktop (please complete the following information):**
 - macOS 13.5
 - python 3.11
 - griptape 0.17.1

**Comment by collindutter** [comment]
Yep, I'm able to reproduce with this:
```python
from griptape.drivers import OpenAiChatPromptDriver
from griptape.structures import Agent


agent = Agent(
    prompt_driver=OpenAiChatPromptDriver(model="gpt-3.5-turbo", max_tokens=4096),
)

agent.run("Hi")
```
```
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4116 tokens (20 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
```

@vasinov why do we override [max_output_tokens](https://github.com/griptape-ai/griptape/blob/main/griptape/drivers/prompt/openai_chat_prompt_driver.py#L54)? Seems like we'd want the `min` behavior from the [parent implementation](https://github.com/griptape-ai/griptape/blob/main/griptape/drivers/prompt/base_prompt_driver.py#L31).

**Comment by nulldiver** [comment]
This didn't actually totally fix the issue. It removes the maximum context length error. But to clarify the overall problem that I'm seeing:

This works:

```
agent = Agent(
    prompt_driver=OpenAiChatPromptDriver(model="gpt-3.5-turbo"),
)
```

But this:

```
agent = Agent(
    prompt_driver=OpenAiChatPromptDriver(model="gpt-4"),
)
```

Or this:

```
agent = Agent()
```

Consistently results in:

`last result: failed (RateLimitError Rate limit reached for 10KTPM-200RPM in organization org-oGWSZQGvT75sDeDR9a1FLwgq on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.`

Setting an arbitrarily low max_tokens, eg:

```
agent = Agent(
    prompt_driver=OpenAiChatPromptDriver(model="gpt-4", max_tokens=200),
)
```

Mitigates against this.
I've confirmed that:
1. Nobody else in the organization is currently using gpt-4, so we are not hitting a tokens per min limit from any other process; and
2. This is not a problem that I encounter with OpenAI's APIs directly unless I'm using multiple concurrent threads on big tasks (and am legitimately pushing that many tokens per minute).

I can just specify gpt-3.5-turbo or be conservative with max_tokens when using gpt-4, so there is a work-around in a sense. The bigger concern was that rate limits were the immediate error when trying out the very first hello-world level agent example in the docs and so my immediate reaction was "ok, well, I guess griptape doesn't work".

**Comment by vasinov** [comment]
@nulldiver, I think I remember seeing this issue come up in some other context before. If I remember correctly, the ultimate problem here is that Griptape always requests the maximum _possible_ number of tokens per each call. In 99.9% of text generations those tokens are never used but the fact that they were _requested_ counts against the rate limit. The per-minute rate limit bucket is never updated with the actual number of tokens returned.

Let me know if you think this is correct and what possible workarounds, besides the ones you've already mentioned, might exist.

**Comment by collindutter** [comment]
@vasinov yeah I think that is the issue based on our past discussions; maybe we shouldn't have these defaults. Either update the [default prompt driver](https://github.com/griptape-ai/griptape/issues/245), or the default max tokens.

**Comment by nulldiver** [comment]
@vasinov - it looks like it.  The tokenizer sets max_tokens to 8184 which isn't a problem on the first request. But on the second request it has already crossed the rate limit. If I wait a minute between chatcompletions, I don't have the problem. I guess the difference I see in gpt-3.5-turbo is that it is requesting 4088 tokens. 8184 is just relatively high to the 10,000 gpt-4 token per minute rate limit that OpenAI set for me but it takes a lot of 4,088 requests to hit the 90,000 limit. I guess this is the "We are prioritizing general access to GPT-4 first and will subsequently raise rate limits automatically as capacity allows." in play.

Changing default prompt driver like @collindutter suggests - to one with a higher rate limit (the 3.5 instruct one is absurd). Or, I suppose not requesting the max -- using tiktoken to estimate actual use and then adding some padding? The parameter is optional on their APIs -- what are they doing when it isn't specified? I tried taking a look through their python APIs but it seems to just pass it through directly and their docs didn't mention how defaults are handled?
