### ISSUE TITLE
Ruleset to output JSON not followed with gpt-3.5-turbo (causing tutorial problem)

### ISSUE THREAD

**Issue by nulldiver** [griptape-ai/griptape#256]
**Describe the bug**
When following the "Building a Conversational Chatbot with Personality Using Griptape's Rulesets", I noticed that if the model is set to "gpt-3.5-turbo" the ruleset for outputting JSON responses is not followed. The error is not handled gracefully by the tutorial code when it attempts to parse a non-JSON response.

**To Reproduce**
Because of https://github.com/griptape-ai/griptape/issues/255, I have been habitually adding the following to agents (and 

    prompt_driver=OpenAiChatPromptDriver(
        model="gpt-3.5-turbo",
        max_tokens=200
    )

I generally have 3.5 specified when experimenting since it is cheaper. I noticed, however, that the tutorial, which specifies JSON responses in a ruleset does not work without changing the model to gpt-4 -- at which point it works as expected. I do not know if this is the chat model not following rules or another issue, since if I just use the OpenAI APIs and specify that responses are to be made as JSON in a system prompt, it seems to comply.

**Expected behavior**
Similar ruleset following across chat models.
Tutorial code that handles unexpected model responses more gracefully. 

**System info:**
griptape version: 0.17.1

**Comment by collindutter** [comment]
Hey @nulldiver!

With some minor rule changes I was able to get it working on `gpt-3.5-turbo` but I had to remove `kiwi_ruleset`. 3.5 seems to have a hard time with both `kiwi_ruleset` _and_ `json_ruleset`.

I'll play with it a bit more to see if I can get it working with both.
```python
from dotenv import load_dotenv
import logging
import json

# Griptape Items
from griptape.drivers import OpenAiChatPromptDriver
from griptape.structures import Agent
from griptape.rules import Rule, Ruleset

# Load environment variables
load_dotenv()

# Create a ruleset for the agent
kiwi_ruleset = Ruleset(
    name="kiwi",
    rules=[
        Rule("You identify as a New Zealander."),
        Rule("You have a strong kiwi accent."),
    ],
)

json_ruleset = Ruleset(
    name="json_ruleset",
    rules=[
        Rule(
            "Output only a JSON object that has the following keys: 'response', 'continue_chatting'."
        ),
        Rule(
            "The 'response' value must be a string that is your response to the user."
        ),
        Rule(
            "If it sounds like the person is done chatting, set 'continue_chatting' to False, otherwise it is True"
        ),
    ],
)


# Create a subclass for the Agent
class MyAgent(Agent):
    def respond(self, user_input):
        agent_response = agent.run(user_input)
        data = json.loads(agent_response.output.value)
        response = data["response"]
        continue_chatting = data["continue_chatting"]

        print("")
        print(f"Kiwi: {response}")
        print("")

        return continue_chatting


# Create the agent
agent = MyAgent(
    rulesets=[json_ruleset],
    logger_level=logging.ERROR,
    prompt_driver=OpenAiChatPromptDriver(model="gpt-3.5-turbo"),
)


# Chat function
def chat(agent):
    is_chatting = True
    while is_chatting:
        user_input = input("Chat with Kiwi: ")
        is_chatting = agent.respond(user_input)


# Introduce the agent
agent.respond("Introduce yourself to the user.")

# Run the agent
chat(agent)

```

**Comment by nulldiver** [comment]
@collindutter - Ok cool, I'm glad that you were able to reproduce and that it is a model issue. That is a good observation on it being the combination -  I got it working together in 3.5-turbo with the following rules:

        Rule("Output only a JSON object that has the following keys: 'response', 'continue_chatting'."),
        Rule("The 'response' value must be a string that is your response to the user."),
        Rule("In the 'response' value, you identify as a New Zealander."),
        Rule("In the 'response' value, you have a strong kiwi accent."),
        Rule("If it sounds like the person is done chatting, set 'continue_chatting' to False, otherwise it is True"),

I'm less concerned that it is a model issue with OpenAI than I would be if it was somehow a Griptape issue with using the model.

**Comment by collindutter** [comment]
@nulldiver Nice on getting it working! @shhlife we should probably update the tutorial to include a variation with a single `Ruleset`.
