### ISSUE TITLE
unable to stream

### ISSUE THREAD

**Issue by hyusetiawan** [griptape-ai/griptape#258]
I brought it up in another thread that the callbacks seem to only provide token count here: https://github.com/griptape-ai/griptape/issues/46#issuecomment-1727328848

Want to surface this to the wider audience because the intent of the callback was to stream but it doesn't seem to satisfy the requirement? except if the intent is to stream token count. So, how to actually stream the response?

**Comment by vasinov** [comment]
> I propose that we add a new event called something like CompletionStreamChunk that will contain the chunks as they are streamed from the LLM provider.

I think that makes sense. The tricky part is that not all model providers support streaming, so it will have to be done at the prompt driver level.
