### ISSUE TITLE
Question regarding debugging prompts and LLM calls

### ISSUE THREAD

**Issue by wemoveon2** [griptape-ai/griptape#266]
I was working through the tutorial on chatbots and encountered an issue where my LLM outputs were not formatted as JSON despite having a `Rule` stating `"Respond only with JSON objects that have the following keys: name, response, favorite_color, continue_chatting."`. 

I wanted to debug this by first confirming that the full prompt is being sent and in the "correct" format, however, despite setting the logging level for the agent to `DEBUG`, all I see during the error is 

```
[09/21/23 16:19:49] INFO     PromptTask bf22640b5ced4b40b7313dd54be1bec5
                             Input: Introduce yourself to the user.
.. [09/21/23 16:19:51] INFO     PromptTask bf22640b5ced4b40b7313dd54be1bec5
                             Output: It's a me! Mario! I'm an Italian plumber with 2 decades of experience. How can I help
                             you today?
It's a me! Mario! I'm an Italian plumber with 2 decades of experience. How can I help you today?
Traceback (most recent call last):
  File "/Users/alan/Projects/learning_ml/tutorials/griptape/chatbots/app.py", line 129, in <module>
    agent.respond("Introduce yourself to the user.")
  File "/Users/alan/Projects/learning_ml/tutorials/griptape/chatbots/app.py", line 28, in respond
    data = json.loads(agent_response.output.value)
  File "/Users/alan/.pyenv/versions/3.9.17/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/alan/.pyenv/versions/3.9.17/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/alan/.pyenv/versions/3.9.17/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Is it possible to see the full request being sent to OpenAI or whichever provider is being used? How would you debug this issue?

**Comment by collindutter** [comment]
Hey @wemoveon2!

Assuming you're using the `OpenAiChatPromptDriver`, you could log [messages](https://github.com/griptape-ai/griptape/blob/main/griptape/drivers/prompt/openai_chat_prompt_driver.py#L63) to see what is being sent to OpenAi. Same goes for [other](https://github.com/griptape-ai/griptape/blob/main/griptape/drivers/prompt/anthropic_prompt_driver.py#L27) Prompt Drivers, you generally want to add a log in the `try_run` method.

I'm going to create a separate issue to add more useful logs that come with the framework so that you can debug Prompt Drivers just by setting the `logger_level`.

**Comment by wemoveon2** [comment]
Hey, thanks for the timely answer, I'll take a look soon.

Also, what are these hashes? e.g `[09/21/23 16:19:51] INFO     PromptTask bf22640b5ced4b40b7313dd54be1bec5`

Is there anything meaningful to be done with these hashes or are these just an implementation detail not meant to be used by the user?

**Comment by collindutter** [comment]
That's the Task's [id](https://github.com/griptape-ai/griptape/blob/main/griptape/tasks/base_task.py#L23). In a Workflow, you can reference parent Tasks by id. Examples here:
- https://docs.griptape.ai/griptape-framework/structures/workflows/
- https://learn.griptape.ai/courses/compare-movies-workflow/03_first_workflow/#code-review
