### ISSUE TITLE
YouTube search tool: Feature request

### ISSUE THREAD

**Issue by ashkaaar** [griptape-ai/griptape#278]
YouTube search tool that lets us search for YouTube videos by keyword, channel ID, or video ID?

This would be super helpful for finding specific videos or channels.

**Comment by ashkaaar** [comment]
If it's not a bad idea, should I start working on it?

**Comment by collindutter** [comment]
Hey @ashkaaar sorry for the slow response! This sounds like a great idea, can you please outline a bit more on what you're thinking?

What kind of use cases would this service? You mentioned search, what about getting video transcriptions? Anything else come to mind?

What activities do you envision this tool having? And what would the schema for those activities look like?
