### ISSUE TITLE
Allow output to be transformed before piping into new task

### ISSUE THREAD

**Issue by WouterDurnez** [griptape-ai/griptape#279]
### Context
I might be overlooking functionality here, but I'm currently struggling with the following. I have a set of prompts that I feed to Claude-instant on Bedrock. In some cases, I want very specific output formatting, such as JSON. The model cannot handle this request every time, so I wrote a small parser to end up with proper JSON.

### Issue
I really love the idea of being able to implement DAGs as Workflows, and they would be very useful. However, I haven't found a way to pass transformed (e.g., JSON parsed) output to new tasks. I could add another Task to make sure it's parsed properly, but that's another API call and I can do it myself.

### Solution
Is there a way to apply post-call operations to output before passing it to another Task?

### Alternatives
I could add new steps or break the pipeline/workflow up into separate parts, but that seems like a less clean solution.

**Comment by collindutter** [comment]
@WouterDurnez does something like [this](https://learn.griptape.ai/courses/compare-movies-workflow/06_workflow_outputs/#code-review) cover what you're looking for?

You can also pass [ task-level rules](https://docs.griptape.ai/reference/griptape/tasks/prompt_task/#griptape.tasks.prompt_task.PromptTask.rules) which you can use to format output.

**Comment by WouterDurnez** [comment]
Hi @collindutter, thanks for the response. I'm not sure what exactly you're hinting at. Do you mean I could build my own tool to parse the JSON? That could work, but looks like a lot of steps for what I'm after.

Discussing this with a colleague, it would appear that my request boils down to this: https://python.langchain.com/docs/modules/chains/foundational/transformation

Is there a way to do this in Griptape without too much overhead, allowing me to use such transformation as part of of Pipeline/Workflow?

The Ruleset is not fully clear to me, but from what I understand it boils down to prompt engineering, under the hood? Unfortunately, my LLM isn't always so reliable. It tends to ignore certain prompt rules every now and then, hence my manual step.

**Comment by collindutter** [comment]
Got it, thank you for clarifying! I was hinting at something like this:
```python
from griptape.structures import Agent
from griptape.rules import Rule
from griptape.drivers import AmazonBedrockPromptDriver, BedrockClaudePromptModelDriver

agent = Agent(
    rules=[Rule("Write your output in a json object with a single key, 'result'")],
    prompt_driver=AmazonBedrockPromptDriver(
        model="anthropic.claude-instant-v1",
        prompt_model_driver=BedrockClaudePromptModelDriver(),
    ),
)

agent.run("Hi how are you?")
```
```
[09/26/23 08:42:15] INFO     PromptTask
                             3b560b9b3ec7413989ec7c5ab6e5ab86
                             Input: Hi how are you?
[09/26/23 08:42:16] INFO     PromptTask
                             3b560b9b3ec7413989ec7c5ab6e5ab86
                             Output: {
                               "result": "I'm doing well, thanks for
                             asking. How about you?"
                             }
```

But I can understand wanting to do this transformation manually, I've also noticed the less powerful models occasionally ignoring prompts.

@vasinov What do you think about this? I can see two paths:
1. Create a `TransformTask` that has a prompt tailored to transforming input data into a specific format. This approach has the downside of not working with Agents since they can only use a single Task.
2. Add a `transform_fn` to `BaseTextInputTask` that allows developers to manually transform the data.

Maybe the ideal solution is a combination of the two?

**Comment by vasinov** [comment]
@WouterDurnez, thanks for the question! Sounds like all you need is a custom task. Here is how I'd implement the LangChain from your link with Griptape:

```python
class TransformationTask(BaseTextInputTask):
    def run(self) -> TextArtifact:
        # you can pull values from the context directly
        text_from_context = self.full_context.get("text")
        
        # or access rendered input directly
        text_from_input = self.input.to_text()
        
        shortened_text = "\n\n".join(text_from_context.split("\n\n")[:3])

        return TextArtifact(shortened_text)


task = TransformationTask(
    context={"text": "my text"}
)

pipeline = Pipeline()

pipeline.add_task(task)
```
Does this achieve what you are trying to do? Or am I still missing something? It would also help to look at a more concrete example of what you are trying to do, if you have one to share.

**Comment by WouterDurnez** [comment]
That would be perfect, as it allows me to interweave such tasks in a workflow DAG. I can add the transformation function as a constructor argument to make it flexible, as @collindutter suggested. Will do it this way, thanks!
