### ISSUE TITLE
Union Syntax Requires Python 3.10

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#299]
We replaced `typing.Union` with the pipe syntax (`|`) in this [PR](https://github.com/griptape-ai/griptape/issues/226), but this is a feature that [requires python 3.10](https://peps.python.org/pep-0604/). We should either bump the required version in `pyproject.toml` or revert the change.

**Comment by vasinov** [comment]
I think itt should work as long as we have annotations exported:

```python
from __future__ import annotations
```

I also run all of my projects on 3.9 to make sure it actually works :)

**Comment by vasinov** [comment]
But...am I [wrong](https://github.com/google/pytype/issues/785#issuecomment-1163993027)?

**Comment by collindutter** [comment]
Ahh, I think you are correct. I was going off a `pyright` error but I had forgot the `annotations` import.
