### ISSUE TITLE
Ability to use griptape lib in an AWS Lambda func without container image 

### ISSUE THREAD

**Issue by kyleroche** [griptape-ai/griptape#314]
**Is your feature request related to a problem? Please describe.**
User would like to use griptape in an AWS Lambda function without having to use container images. 

**Describe the solution you'd like**
A document describing how to accomplish. 

**Describe alternatives you've considered**
Container images have been tried. Current size of the lib (being worked) is a challenge. User also cannot use layers w/ container images b/c they have private python packages required. 

**Additional context**
Original request from [Discord user Bjorg](https://discord.com/channels/1096466116672487547/1096466118048231579/1158817493238947930). Please follow up when worked.

**Comment by derekpai** [comment]
related to #134

Current workaround for cold start is to use Lambda provisioned concurrency with container images, but that's not awesome.

**Comment by collindutter** [comment]
This is possible now that core dependencies are minimal and 3P dependencies are optional.
