### ISSUE TITLE
Add an issue template for new tools

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#330]
In the past, multiple developers either submitted a PR or requested a tool in issues. I would like to have an issue template (in addition to feature and bug templates) that developers can use when requesting a new tool.

I think it should have the following fields but let's discuss more:

* Tool Name
* Tool Description
* List of Proposed Activities
* Examples w/ Griptape Agents

**Comment by andrewfrench** [comment]
Related to #459

**Comment by collindutter** [comment]
@andrewfrench do we still need this with the latest contributing guidelines?

**Comment by collindutter** [comment]
Closing as per https://github.com/griptape-ai/griptape/pull/459
