### ISSUE TITLE
Chain of thought "caches" activity name

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#336]
**Describe the bug**
Agents that have access to activities that can load values from memory or pass content directly don't always switch to the correct activity when presented with novel information.

For example, say there is an agent that uses the `FileManager` tool. The tool has to activities for saving data to disk:

* `save_memory_artifacts_to_disk`
* `save_content_to_file`

When presented with a query like

> Do X and store the result in result.txt

The LLM could come up with the following chain of thought:

> First, I will use tool `ToolX` to do X and then I will use FileManager activity "save_content_to_file" to save it in result.txt

After the first subtask is complete and the value from `ToolX` is stored in memory, the LLM sometimes attempts to still `save_content_to_file` even though `save_memory_artifacts_to_disk` is obviously the correct way to do it.

**To Reproduce**
```python
from griptape.structures import Agent
from griptape.tools import WebScraper, FileManager

agent = Agent(
    tools=[WebScraper(), FileManager()]
)

agent.run("get content from www.griptape.ai and store it to griptape.txt")
```

**Additional Context**
Often, the LLM won't say the activity explicitly and will just say something like "I will save the result to result.txt by using FileManager." In that case it always picks the correct activity at the end.

**Comment by collindutter** [comment]
Closing as a lot has changed WRT how we execute Tools. Can re-open if we can find another reproducible scenario.
