### ISSUE TITLE
Validate tool activities that have `pass_artifact`set to True

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#34]
Tool activities that have `pass_artifact` set to True should be validated during instantiation with an [attrs validator](https://www.attrs.org/en/stable/examples.html#validators) and throw a `ValueError` if the tool doesn't have any ramps.

**Comment by collindutter** [comment]
@vasinov this can be closed, right?

**Comment by vasinov** [comment]
Yep. Closing.
