### ISSUE TITLE
Improve prompt driver integration tests

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#356]
Our current prompt driver integration tests (/tests/integration/tasks/test_prompt_task.py) are failing. We're using the presence of a sentinel work "ship" in the model response to determine whether or not the prompt has been correctly supplied to the model, but several return responses that do not follow the rules defined by the test prompt. These tests are effectively testing the rule-following capability of each model rather than the functionality of the prompt driver.

We should find a way to structure the tests that don't depend on the models returning a response that follows the rules, because this is outside the scope of Griptape.

**Comment by derekpai** [comment]
#377
