### ISSUE TITLE
Execute integration tests on commit to `main`

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#377]
We have integration tests, but don't run them frequently. We choose not to run tests that require credentials on external contributions, like pull requests, because this requires exposing secrets. We should leverage our more robust end-to-end integration tests to

 - increase confidence in changes
 - quickly identify regressions
 - better coverage for components with trivial unit tests

By only applying integration tests to commits to `main`, we prevent exposing secrets to outside contributors. We also reduce the frequency with which we run heavier, more involved tests, reducing our test execution times (which can be annoying when making small changes in a PR), reducing resource consumption (Github Actions runner time, token consumption, reading/writing to real external services), and ultimately reducing costs.

**Comment by collindutter** [comment]
Implemented via https://github.com/griptape-ai/griptape/pull/795
