### ISSUE TITLE
Generalized Text Search Solution

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#383]
Users want to use Griptape to perform web searches with various search backends (https://github.com/griptape-ai/griptape/pull/296, and https://github.com/griptape-ai/griptape/pull/289). Similar to how we search vectors, I propose adding a generalized solution for non-vector search. 

- Tools
    - TextQueryClient (Replaces WebSearch)
- Engines 
    - TextQueryEngine
- Drivers 
    - GoogleSearchDriver
    - BingSearchDriver
    - DuckDuckGoSearchDriver
    - ArxivSearchDriver
- Tasks
    - TextQueryTask (already exists, would use new TextQueryEngine)

**Comment by shhlife** [comment]
Can we include image search as part of this offering? For drivers, please also add Unsplash.

**Comment by ccr-fan-3000** [comment]
Any plans to implement this soon?
