### ISSUE TITLE
Redis Conversation Memory Driver

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#389]
Users want to store Conversation Memory in other databases besides DynamoDb. Redis is a fast, flexible, and popular option. I propose adding a `RedisConversationMemoryDriver`.

**Comment by torabshaikh** [comment]
Hi @collindutter I would like to work on it.

**Comment by qwe321389yfs8t7huqd89q** [comment]
What is status of that? I can't see any commits on fork @torabshaikh

**Comment by torabshaikh** [comment]
> What is status of that? I can't see any commits on fork @torabshaikh

Hi @qwe321389yfs8t7huqd89q , I was busy with other work. I have started working on it again recently.

**Comment by vachillo** [comment]
@torabshaikh thanks for the contribution!
