### ISSUE TITLE
Add Stream functionality to the Chat utility

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#405]
[x ] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the solution you'd like**
Now that we have the Stream utility, it would be very helpful to add the functionality to the Chat utility. Preferably it would just be a parameter you pass.

`Chat(agent, stream=True).start()`

**Comment by mattma1970** [comment]
Hey, I've been playing with the Streaming class a bit and would like to put this together.

**Comment by shhlife** [comment]
I modified my initial request to focus on `stream=True`, so I replaced the method `run` with `start` (since that's what Chat uses), and also removed the initial message.

so instead of: `Chat(agent, stream=True).run("Howdy!")` it's `Chat(agent, stream=True).start()`
