### ISSUE TITLE
AwsLambdaExecutor

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#43]
We want to enable developers who want to deploy tools in the cloud serverlessly by introducing `AwsLambdaExecutor`—one of the first serverless platform integrations.

**Comment by atcol** [comment]
I'd like to pick this up. Do you have further details on how this should be structured / approached?

**Comment by vasinov** [comment]
I think @collindutter might've done some work on this already. @collindutter, could you share some details? Thanks!

**Comment by collindutter** [comment]
Yes, I already created an executor (https://github.com/griptape-ai/griptape/issues/43) that works in a lambda environment. Though this is basically a modification of the LocalExecutor. A proper AWSLambdaExecutor would likely invoke a lambda function configured with a tool?

**Comment by kyleroche** [comment]
Can you throw a quick doc PR up along with that for testing?

**Comment by collindutter** [comment]
@atcol the changes I had made on #48 are being moved to `LocalExecutor` in case you wanted to pick this up again.

**Comment by atcol** [comment]
Would you like me to move that to LocalExecutor - is that what you mean?

**Comment by vasinov** [comment]
Now that the executors are gone, this issue is no longer relevant.
