### ISSUE TITLE
Feature Request: Addition of a Requests Tool

### ISSUE THREAD

**Issue by ashkaaar** [griptape-ai/griptape#438]
**Is your feature request related to a problem? Please describe.**
Manually addding query strings to URLs or form-encode my POST data while making HTTP requests is frustrating. The process is not as streamlined as I would like it to be.

**Describe the solution you'd like**
I would like to propose the addition of a `requests` tool. This tool should provide a higher level of abstraction for making HTTP requests, simplifying the process and making it more efficient. It should support several types of requests such as GET, POST, and PATCH, and have built-in mechanisms for error handling. Additionally, it would be beneficial if the tool could provide asynchronous methods for improved performance when making multiple requests.

**Describe alternatives you've considered**
An alternative could be to use Python's built-in `requests` module directly. However, this does not provide the same level of abstraction, integration, and convenience as a dedicated `requests` tool within `griptape` would.

**Additional context**
The `requests` tool in `langchain` has proven to be very useful and efficient. It is integrated with other parts of the library and works seamlessly with them. I believe that a similar tool in `griptape` would greatly enhance the functionality and user experience of the framework.

- [x]  I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Comment by collindutter** [comment]
@ashkaaar we've already got the [RestApiClient](https://docs.griptape.ai/griptape-tools/official-tools/rest-api-client/), perhaps we just need to make some enhancements to this?

**Comment by collindutter** [comment]
Hey @ashkaaar just following up on this. Are there features missing in the `RestApiClient` that you'd like to see?

**Comment by collindutter** [comment]
@ashkaaar I'm going to close this issue. Feel free to reopen if you have any feedback!
