### ISSUE TITLE
GooglePromptDriver

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#44]
In order to start experimenting with PaLM models, we need to implement a new driver for Google Cloud `GooglePromptDriver` that can execute models on Google AI platform. We should be able to use their official [Python SDK](https://cloud.google.com/ai-platform/training/docs/python-client-library) to accomplish this goal.

**Comment by vasinov** [comment]
@kyleroche, I know that you've been working on this some. What is currently missing?

**Comment by derekpai** [comment]
Evaluate in a month

**Comment by derekpai** [comment]
come back to this in De (James?)

**Comment by 101steve11** [comment]
Its January have we made anyt progress in using Griptape with Google,,,,

**Comment by collindutter** [comment]
Closed by https://github.com/griptape-ai/griptape/pull/698
