### ISSUE TITLE
Enhancement: Would like to explicitly expose the encoding to be used by `open()` inside TextLoader

### ISSUE THREAD

**Issue by br-moriarty** [griptape-ai/griptape#444]
[x ] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
We would like to support collaborators working on different operating systems. Our source data is utf-8 encoded. For users on Windows, however, because `open` defaults to whatever encoding is returned by `locale.getencoding` we hit errors when characters in our source data are unknown to cp1252.

**Describe the solution you'd like**
It seems like a natural property to expose to expose on `TextLoader`.

**Describe alternatives you've considered**
If intention is to enforce utf-8, another option is to enforce it explicitly in the `open` call, as utf-8 is only default on some operating systems.

**Comment by collindutter** [comment]
@br-moriarty this has been implemented in https://github.com/griptape-ai/griptape/pull/445 which should be released soon.

**Comment by ashkaaar** [comment]
@collindutter that was super quick, impressive
