### ISSUE TITLE
Capture task outputs in a stream

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#46]
As structures execute tasks, users want to see task outputs as stream events.

I propose adding Python iterator support to structures and implementing `__iter__` and `__next__` methods. This way users can execute structures like this:

```python
for event in Agent().run():
    print(event.value)
```

**Comment by collindutter** [comment]
@vasinov Wouldn't implementing `__iter__` and `__next__` methods require us to iterate over the structure class as opposed to the run method? Might it be better to use generators with `yield`?

**Comment by vasinov** [comment]
@collindutterm, Indeed, using generators would be better. Wrote up this issue too quickly and had generator and iterable implementations mixed up in my head 😆.

**Comment by collindutter** [comment]
@vasinov what do you think about emitting subtasks too? Necessary for any user interface that wants to show the entire flow.

**Comment by vasinov** [comment]
@collindutter subtasks should be emitted for sure also.

**Comment by vasinov** [comment]
Update on the issue: @collindutter is working on this after we dramatically simplified the initial design proposal. Should be added in the next version of Griptape.

**Comment by collindutter** [comment]
@vasinov we can close this, right?

**Comment by vasinov** [comment]
Yep, closing.

**Comment by hyusetiawan** [comment]
@vasinov apologies for bringing up an old thread, but I am not sure how to actually stream the text output? The examples and the event object only support token_count, ex: `e.token_count` whereas I want to stream the text itself, is there an example I can follow for that?

<img width="580" alt="Screenshot 2023-09-20 at 2 23 47 AM" src="https://github.com/griptape-ai/griptape/assets/1062920/78fc96d3-b3bd-4a1e-aea9-c4a59d8d1d01">
