### ISSUE TITLE
GPTQ, GGUF, AWQ formats of LLM models doesn't work

### ISSUE THREAD

**Issue by musralina** [griptape-ai/griptape#468]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
Griptape does not support GPTQ, GGUF, AWQ formats of model

**To Reproduce**
when you use the code https://docs.griptape.ai/latest/griptape-framework/structures/prompt-drivers/#hugging-face-hub, and instead of "tiiuae/falcon-7b-instruct" model use for example "TheBloke/Phind-CodeLlama-34B-v2-GPTQ". It does not work, although with fallcon model it works.
If use the model not in bin format, I get the WARNING after waiting about a minute or more: WARNING:root:<RetryCallState 140407574546848: attempt #1; slept for 0.0; last result: failed (KeyError 0)>

**Expected behavior**
I expect AI starts to generate the answer to the question.

**Screenshots**
No screenshot

**Desktop (please complete the following information):**
Sagemaker + instance ml.g5.2xlarge

**Additional context**
none

**Comment by musralina** [comment]
it works without Griptape, with Griptape it fails.

from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed, TextStreamer
from auto_gptq import exllama_set_max_input_length

model_name_or_path = "TheBloke/Phind-CodeLlama-34B-v2-GPTQ"
model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
                                             device_map="auto",
                                             trust_remote_code=False,
                                             revision="main") 
model = exllama_set_max_input_length(model, max_input_length=12288)
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, use_fast=True)

input_ids = tokenizer(full_prompt, return_tensors='pt').input_ids.cuda()
streamer = TextStreamer(tokenizer)
output = model.generate(inputs=input_ids, streamer=streamer, temperature=0.1, do_sample=True, top_p=0.95, top_k=40, max_new_tokens=2048)

**Comment by collindutter** [comment]
@musralina can you please share the full stack trace? It will retry the request 10 times and then should spit something out. You can also lower the retry amount by setting `max_attempts` on the Prompt Driver.

**Comment by collindutter** [comment]
Closing for now as we don't have enough information to reproduce the issue. @musralina if you are able to share a minimally reproducible example in Griptape we can re-open.
