### ISSUE TITLE
Add image-to-text support

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#500]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
Griptape lacks support for image-to-text workflows.

**Describe the solution you'd like**
Support for image-to-text workflows:
- ImageToTextTask
- ImageToTextEngine
- ImageToText drivers for each supported provider (Textract, OpenAI Vision, etc.)
- Model drivers for providers offering multiple models, if applicable

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by collindutter** [comment]
This has been implemented via Vision Drivers.
