### ISSUE TITLE
Explore support for local StableDiffusion models

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#504]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
Some organizations must use self-hosted or local model deployments. Some drivers might support self-hosted models through configuration of the API endpoint, but local models might require additional work.

**Describe the solution you'd like**
Clearly defined and documented support for local and self-hosted models.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mgcollie** [comment]
Thanks @andrewfrench 🙏

**Comment by collindutter** [comment]
Is there a particular method of interacting with local models you're interested in? We're already looking into support for [Text Generation Interface](https://huggingface.co/docs/text-generation-inference/index) via #89 which should allow for local models.

**Comment by mgcollie** [comment]
@collindutter I was thinking of maybe creating a driver for this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API for interacting with stable-diffusion locally in particular.

**Comment by mgcollie** [comment]
@collindutter maybe I can just use griptapes RestApiClient to do what I need. I'll poke around at that this afternoon

**Comment by mgcollie** [comment]
yeah that works.

**Comment by collindutter** [comment]
@mgcollie the `RestApiClient`, or even a custom Tool, sounds like a suitable solution for now. But lets keep this issue open so we can continue evaluating a long term solution here. 

Regarding the Driver, I'd like to avoid reliance on WebUI, feels a little off to me. What are some other options for getting SD running locally?
