### ISSUE TITLE
PythonTask - a task to just execute python code w/out calling the LLM

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#517]
- [ x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
Each task currently requires an LLM to execute it. It would be very handy to be able to have a task that just executes Python code w/out needing to ping the LLM.

**Describe the solution you'd like**
Simple PythonTask that takes an input and returns the output.

**Describe alternatives you've considered**
We could use ToolTask but from what I understand that still requires an LLM call.

**Comment by collindutter** [comment]
Closed by https://github.com/griptape-ai/griptape/pull/541
