### ISSUE TITLE
Resolve Pyright errors

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#519]
We're using [Pyright](https://github.com/microsoft/pyright) as a static type checker for our Python code. The rules enforced by Pyright are much stricter than those typically enforced natively by an IDE like Visual Studio, PyCharm, or other tools, so a large portion of the framework does not meet Pyright's standard. Pyright currently reports about 160 errors on our `dev` branch that we should resolve before we're able to enforce the standard on new PRs with code checks and pre-commit hooks.

- [x] #577
- [x] chunkers/
- [x] #578
- [x] #579
- [x] #580
- [x] #581
- [x] #582
- [x] #583
- [x] #584
- [x] #585
- [x] #586
- [x] mixins/
- [x] rules/
- [x] schemas/
- [x] structures/
- [x] summarizers/
- [x] #576
- [x] templates/
- [x] tokenizers/
- [x] tools/
- [x] utils/

**Comment by derekpai** [comment]
break this issue down into multiple tasks
