### ISSUE TITLE
Figure out how to fix `TestOpenAiEmbeddingDriver` to run in GitHub actions

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#52]
Tests in `TestOpenAiEmbeddingDriver` run correctly locally but hang on GitHub.

Current hypothesis is that `pinecone.Index` in `PineconeVectorStorageDriver` either makes requests that hang forever or mismanages thread pools.

Our current fix is to move those tests outside of `unit` into `integration`, which don't yet run on GitHub.

**Comment by collindutter** [comment]
@vasinov it seems that you've already [resolved](https://github.com/griptape-ai/griptape/blob/main/tests/unit/drivers/embedding/test_openai_embedding_driver.py) this?
