### ISSUE TITLE
Custom rules appear to not have an impact on the results

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#55]
**Describe the bug**
Custom rules don't appear to have an impact on Agents or Pipeline tasks.

**To Reproduce**
```
from griptape.structures import Agent
from griptape.rules import Rule

agent = Agent(
  rulesets = [
    Rule("Always reply backwards")
  ]
)
agent.run("Say hello")
```

**Expected behavior**
`Output: ayot uoy tsissa I nac woH !olleH`

**Actual behavior**
`Output: Hello! How can I assist you today?`

**Additional context**
I may be using rules incorrectly - is this the expected way to use them?

**Comment by vasinov** [comment]
Great bug report—thanks for using a template :). The right way to use this field is to pass rulesets explicitly, not rules. Here is a working example:

```python
from griptape.rules.ruleset import Ruleset
from griptape.structures import Agent
from griptape.rules import Rule

agent = Agent(
  rulesets=[
    Ruleset(
        name="funny talker",
        rules=[Rule("Always reply backwards")]
    )
  ]
)

agent.run("Say hello")
```

I added an issue to cover it more in the docs: https://github.com/griptape-ai/griptape-docs/issues/29
