### ISSUE TITLE
Running a Pipeline with a FineTuned OpenAI Model Fails

### ISSUE THREAD

**Issue by jimatregrello** [griptape-ai/griptape#564]
Because FT models start with "ft", the following line fails

`tokens = next(v for k, v in self.MODEL_PREFIXES_TO_MAX_TOKENS.items() if self.model.startswith(k))
`
Line 47: openai_tokenizer.py

**Comment by collindutter** [comment]
Thanks for the report @jimatregrello. Looking into a resolution.

**Comment by collindutter** [comment]
Hi @jimatregrello, some updates have been made to the framework that should improve this use-case. You can now pass in a custom tokenizer to `OpenAiChatPromptDriver` which defines values for `max_input_tokens` and `max_output_tokens`. [This example](https://github.com/griptape-ai/griptape/issues/601#issuecomment-2025836660) shows one such example.

I am going to close this issue but please feel free to re-open if you have any questions.
