### ISSUE TITLE
SlackClient

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#592]
- [ x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
It would be helpful to have a SlackClient that would allow Agents, Pipelines, and Workflows to interact with Slack.

**Describe the solution you'd like**
I would like to be able to provide a SlackClient to an Agent so it can send messages, images, and more. 

**Describe alternatives you've considered**
I've created a simple Chatbot that can respond to posts - but it only responds with text. Ideally we have a Client that can work with the slack api to do more interesting things - upload images, get information about the user, etc.

**Comment by collindutter** [comment]
@shhlife We don't have any plans to create a `SlackClient` Tool as part of Griptape's included Tools, but this would be a great candidate for the [Griptape Tool Template](https://github.com/griptape-ai/tool-template).
