### ISSUE TITLE
Storing Vectors in MongoDbAtlasVectorStoreDriver won't return results

### ISSUE THREAD

**Issue by schnelldigital** [griptape-ai/griptape#600]
- [X] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
If you upsert text-artifacts as vectors instead with a LocalVectorStorageDriver into a MongoDbAtlasVectorStoreDriver, no questions will be answered. 
You'll see the vectors corresponding in the MongoDB database (so, the connection is OK and the storing-procedure is fine) but equal queries will be empty, no matter if you use the Chat-class or the agent itself. 

**To Reproduce**
```
from griptape.drivers import MongoDbAtlasVectorStoreDriver, OpenAiEmbeddingDriver
from griptape.loaders import WebLoader
import os

# Initialize an embedding driver
embedding_driver = OpenAiEmbeddingDriver(api_key=os.getenv("OPENAI_API_KEY"))

# Initialize the vector store driver
vector_store = MongoDbAtlasVectorStoreDriver(
    connection_string="mongodb+srv://########.mongodb.net/?retryWrites=true&w=majority",
    database_name="test-db",
    collection_name="vector",
    embedding_driver=embedding_driver,
)

# Load artifacts from the web
artifacts = WebLoader(max_tokens=200).load("https://www.griptape.ai")

# Upsert the artifacts into the vector store
vector_store.upsert_text_artifacts(
    {
        "griptape": artifacts,
    }
)

engine.vector_store_driver.load_entries()
result = vector_store.query(query="what is griptape?")
print(result)
```

The printed result will be an empty array.
If you exchange the MongoDbAtlasVectorStoreDriver with a LocalVectorStoreDriver, you'll get correct results for your query.

**Expected behavior**
Same results of query independently, which vector-store is used.

**Additional context**
You can use any tutorial/example in the Griptape-Docs, no matter if you search a website or working with the Chat-class, you won't get any results.

I tried to call "vector_store_driver.load_entries()" before the query to ensure, the vectors will be loaded, but this doesn't result in a different behavior.

**Comment by collindutter** [comment]
Hey @schnelldigital, thanks for the issue report! At a glance it looks like it's because you're not specifying the `namespace` argument to `query`; it should be set to `"griptape"`. This appears to be an issue in our documentation, we will get that fixed ASAP.

**Comment by schnelldigital** [comment]
Hey @collindutter. Thanks for your fast reply!
I'll test it as soon as possible. But are you sure, as the Chat-class didn't help as well? Or do we have two separate issues there?

**Comment by schnelldigital** [comment]
Hey @collindutter - i just tested your advice. 
But unfortunately no change in results. Please see the screenshot attached.
<img width="768" alt="Screenshot" src="https://github.com/griptape-ai/griptape/assets/35833375/9788dcf7-46fe-4ed2-b023-8e01cd7d6b28">

**Comment by schnelldigital** [comment]
hey @vachillo. Thanks for your response.

You mean like this? 

```
from griptape.drivers import MongoDbAtlasVectorStoreDriver, OpenAiEmbeddingDriver
from griptape.loaders import WebLoader
import os


# Initialize an embedding driver
embedding_driver = OpenAiEmbeddingDriver(api_key=os.getenv("OPENAI_API_KEY"))

# Initialize the vector store driver
vector_store = MongoDbAtlasVectorStoreDriver(
    connection_string="mongodb+srv://xxxxxxxxxxxxx",
    database_name="griptape-demo2",
    index_name="vector_index",
    collection_name="vector",
    embedding_driver=embedding_driver,
)

# Load artifacts from the web
artifacts = WebLoader(max_tokens=200).load("https://www.griptape.ai")

# Upsert the artifacts into the vector store
vector_store.upsert_text_artifacts(
    {
        "griptape": artifacts,
    }
)

result = vector_store.query(query="what is griptape?", namespace="griptape")
print(result)

```

This won't give any results either.

**Comment by vachillo** [comment]
> hey @vachillo. Thanks for your response.
> 
> You mean like this?
> 
> ```
> from griptape.drivers import MongoDbAtlasVectorStoreDriver, OpenAiEmbeddingDriver
> from griptape.loaders import WebLoader
> import os
> 
> 
> # Initialize an embedding driver
> embedding_driver = OpenAiEmbeddingDriver(api_key=os.getenv("OPENAI_API_KEY"))
> 
> # Initialize the vector store driver
> vector_store = MongoDbAtlasVectorStoreDriver(
>     connection_string="mongodb+srv://xxxxxxxxxxxxx",
>     database_name="griptape-demo2",
>     index_name="vector_index",
>     collection_name="vector",
>     embedding_driver=embedding_driver,
> )
> 
> # Load artifacts from the web
> artifacts = WebLoader(max_tokens=200).load("https://www.griptape.ai")
> 
> # Upsert the artifacts into the vector store
> vector_store.upsert_text_artifacts(
>     {
>         "griptape": artifacts,
>     }
> )
> 
> result = vector_store.query(query="what is griptape?", namespace="griptape")
> print(result)
> ```
> 
> This won't give any results either.

does the index you specified in `index_name` exist on the collection? If not, [here is the Atlas docs](https://www.mongodb.com/docs/atlas/atlas-vector-search/create-index) that explain how to create one.

**Comment by collindutter** [comment]
Adding onto this, here is a sample index definition:
```json
{
  "fields": [
    {
      "numDimensions": 1536,
      "path": "vector",
      "similarity": "euclidean",
      "type": "vector"
    },
    {
      "path": "namespace",
      "type": "filter"
    }
  ]
}
```

**Comment by schnelldigital** [comment]
That's it. Due to the docs I assumed, that like the collection the Index will be automatically generated.
Maybe that's a task for an updated documentation.
👏 Thank you very much!
