### ISSUE TITLE
Ollama Prompt Driver Support

### ISSUE THREAD

**Issue by benwilde** [griptape-ai/griptape#601]
**Is your feature request related to a problem? Please describe.**
Would like to ability to use Griptape with any Ollama compatible API including Ollama itself, and other implementations such as https://github.com/BLaZeKiLL/Spin-O-Llama

**Describe the solution you'd like**
Implement and maintain Ollama API support as a Prompt Driver in Griptape 

**Describe alternatives you've considered**
Writing it myself but then it wouldn't be very good. 

**Additional context**
LangChain and Llama Index both provide the means to use LLMs via Ollama API.

**Comment by benwilde** [comment]
If / When someone picks this up here are a few more thoughts:

* please expose all the API parameters via the class so they can be passed in (for the Llama Index implementation they didn't do this so you need to add additional kwargs which is OK but would be cleaner not having to do that).
* please make whether the result from the API should stream or not an option. Langchain doesn't, it requires it to be a streaming response but Llama Index doesn't. Nice if you can have the option rather than the expectation of a stream. 

Thanks!

**Comment by LeventeNagy** [comment]
I would also second this, would be a great opportunity to use Ollama with Griptape, specially with all API parameters.
As for now I am using Ollama trough LiteLLM but unfortunately a lot of functionality fails because it can't take advantage of the full API

Hope this will be taken into consideration in the future.

**Comment by JacobGoldenArt** [comment]
Have a look at the Ollama repo, they just released a OpenAI compatible api, that maps to most of the Ollama api.

**Comment by LeventeNagy** [comment]
> Have a look at the Ollama repo, they just released a OpenAI compatible api, that maps to most of the Ollama api.

Yes I have seen that, unfortunately tried several variations and it is not working with griptape

**Comment by collindutter** [comment]
@LeventeNagy Can you expand a bit more on which issues you faced with the OpenAI compatible API? I would expect it is a very similar issue to https://github.com/griptape-ai/griptape/issues/512

**Comment by benwilde** [comment]
This post isn't likely to be helpful sorry. While I have successfully used the OpenAI support in Griptape to talk to Predibase (see code below) I too have failed to get this to work with the Ollama OpenAI endpoint. Even when following the Ollama OpenAI instructions.

I can get the curl command to work on my laptop (and also when using the OpenAI driver directly to talk to Ollama from the same venv) but when I go to use the Griptape code below modified with with the same base_url as the curl command I get a 404 error back. I have tried several variations of base_url and nothing works. 

I looked at the griptape source code for [OpenAiCompletionPromptDriver](https://github.com/griptape-ai/griptape/blob/f96af2e4215cfc3b80918fc438d22688078d5da6/griptape/drivers/prompt/openai_completion_prompt_driver.py#L13) and the base_url is just passed through to the OpenAI driver. Nothing weird there I could see (and besides, it works with Predibase).

So it's the combination of Ollama's implementation and Griptape's usage that don't like each other. I haven't tried to see the actual URL that is being sent from the OpenAI client to Ollama yet. 

Here is the code that works from Griptape with Predibase's OpenAI driver:

```
import logging, os    
from griptape.structures import Agent
from griptape.utils import Chat  
from griptape.config import StructureConfig, StructureGlobalDriversConfig
from griptape.drivers import OpenAiCompletionPromptDriver

# Create the agent without logging unless an ERROR  
agent = Agent(
    config=StructureConfig(
        global_drivers=StructureGlobalDriversConfig(
            prompt_driver=OpenAiCompletionPromptDriver(
                api_key=os.environ["PREDIBASE_API_KEY"],
                temperature=0.1,
                model="",
                base_url="https://serving.app.predibase.com/7f259d/deployments/v2/llms/mistral-7b-instruct/v1",
                max_tokens=200
            )
        )
    ),
    logger_level=logging.ERROR      
)

# Begin Chatting
Chat(agent).start()
```

**Comment by collindutter** [comment]
Thanks @benwilde this is very helpful. We'll keep you posted.

**Comment by collindutter** [comment]
Hey all, it appears that we can integrate with Ollama through the [OpenAI Integration](https://ollama.com/blog/openai-compatibility).

`ollama pull llama2`

```python
from griptape.drivers import OpenAiChatPromptDriver
from griptape.config import StructureConfig, StructureGlobalDriversConfig
from griptape.structures import Agent
from griptape.tokenizers import HuggingFaceTokenizer
from transformers import LlamaTokenizerFast

agent = Agent(
    config=StructureConfig(
        global_drivers=StructureGlobalDriversConfig(
            prompt_driver=OpenAiChatPromptDriver(
                model="llama2",
                base_url="http://localhost:11434/v1",
                api_key="ollama",
                tokenizer=HuggingFaceTokenizer(
                    tokenizer=LlamaTokenizerFast.from_pretrained(
                        "meta-llama/Llama-2-7b-chat-hf"
                    ),
                    max_output_tokens=1024,
                ),
            ),
        ),
    )
)

agent.run("Write me a poem about pirates.")
```

```
[03/28/24 12:14:04] INFO     PromptTask e12e1672119e4fbeb9e90ebe768a2964
                             Output: Ahoy, matey! Here be a poem for ye:

                             Pirates of the seven seas,
                             With swords and cutlasses, they'll freeze,
                             Their treasure hoard, a sight to see,
                             Gold doubloons, shiny as can be.

                             They sail the ocean blue,
                             In search of adventure, new,
                             From the Caribbean to the Indies,
                             Their legend grows with each passing breeze.

                             With a "Yo ho ho!" and a grin,
                             They pillage and plunder, spin,
                             Their Jolly Roger flies high,
                             As they sail into the sky.

                             But beware, ye landlubbers,
                             For these pirates be fierce and rough,
                             They'll steal yer treasure, and maybe even yer soul,
                             So keep yer valuables safe, or ye'll be in a hole!

                             So hoist the sails, me hearties,
                             And let's set sail on the high seas,
                             For adventure, gold, and glory,
                             Are waiting for us, with open arms, me mateys!
```

**Comment by collindutter** [comment]
Going to close this issue as basic support appears to be working. Please feel free to re-open if anyone runs into more advanced use-case that do not!
