### ISSUE TITLE
Remove `create_index()` on all `VectorStoreDriver`s 

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#607]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

only a subset of `VectorStoreDriver`s have a `create_index()`. this should be deprecated and removed from existing drivers and removed from the docs.

**Comment by collindutter** [comment]
Based on an internal conversation we landed on _not_ implementing these kinds of calls in Drivers. We only want to work with data APIs, not infrastructure APIs.

I think this issue should be repurposed to _remove_ the `create_index` calls from Drivers that do have it.

**Comment by vachillo** [comment]
done
