### ISSUE TITLE
Prompt Drivers Crash When Streaming Without A Structure

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape#643]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
Prompt Drivers require `structure` to be set in order to publish `CompletionChunkEvents`.

**To Reproduce**
1. Create a Prompt Driver without a Structure.
2. Try streaming.
3. Observe a crash [here](https://github.com/griptape-ai/griptape/blob/dev/griptape/drivers/prompt/base_prompt_driver.py#L79).

**Expected behavior**
Prompt Drivers should not depend on a Structure just to stream. Perhaps they should take in an `event_listener: EventListener` instead of a `structure: Structure`. If a Structure is the one using the Prompt Driver, it can provide an `EventListener`. Otherwise we can default one.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
[Add any other context about the problem here.](https://github.com/griptape-ai/griptape/pull/591/files#r1484815191)

**Comment by torabshaikh** [comment]
@collindutter Can I do it?

**Comment by collindutter** [comment]
@torabshaikh sure! Thanks :)

**Comment by collindutter** [comment]
Hey @torabshaikh, just checking in to see if you had any questions on this! Let us know if there's anything we can do to help.

**Comment by torabshaikh** [comment]
@collindutter I have started working on it. I will surely ask you if I have any doubts.

**Comment by torabshaikh** [comment]
Hi @collindutter , I have replaced `structure: Structure` with  `event_listener: EventListener` but there is an issue. `preprocess` method inside `PromptTask` takes a structure. And an structure can have multiple `event_listener`. This is breaking the flow since we can't assign a list of `EventListener` to a single `EventListener` .

**Comment by collindutter** [comment]
@torabshaikh can you make it so the Prompt Driver takes `event_listeners: list[EventListener]` instead?

**Comment by torabshaikh** [comment]
Hi @collindutter I just submitted #914 for this. Please review.
