### ISSUE TITLE
Add Gemini Embedding Driver

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#647]
Create an Embedding Driver supporting the Google Vertex AI API.

[Documentation](https://cloud.google.com/vertex-ai/docs/generative-ai/embeddings/get-text-embeddings)

**Comment by bjorger** [comment]
As it seems, there is another embeddings model as well, provided by google.
It's called "model/embedding-001" and is mentioned in the [Gemini models page](https://ai.google.dev/models/gemini#embedding).
