### ISSUE TITLE
Add Google Imagen Image Generation Driver

### ISSUE THREAD

**Issue by andrewfrench** [griptape-ai/griptape#649]
Add an Image Generation Driver supporting Google Imagen using the Vertex AI API.

[Documentation](https://cloud.google.com/vertex-ai/docs/generative-ai/image/overview)

**Comment by collindutter** [comment]
We ultimately ended up implementing Google Gemini APIs, not Google Vertex APIs. Google Gemini does not provide an API for image generation at this time.

Going to close this so we can consider https://github.com/griptape-ai/griptape/issues/651 finished, but we can re-open if there is ever work to create a suite of Vertex Drivers.
