### ISSUE TITLE
Build a simple pipeline documentation doesn't currently work

### ISSUE THREAD

**Issue by mgcollie** [griptape-ai/griptape#65]
**Describe the bug**
I'm trying to follow the example here: https://docs.griptape.ai/en/latest/griptape-framework/#build-a-simple-pipeline and the example fails when trying to run it. It's throwing a value error `ValueError: activity query doesn't exist`. This is on windows 10, using python 3.10.8 and I also tried with python 3.11.3

**To Reproduce**
1. create a new virtual environment
2. pip install griptape griptape-tools 
3. copy the example into main.py
4. try to run main.py using the interpreter for the venv

**Expected behavior**
I expected the program to run without errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Version: 22H2
 - Build: 19045.2965

**Comment by mgcollie** [comment]
The same issue exists when trying to use the examples in the [Tool Memory Documentation](https://docs.griptape.ai/en/latest/griptape-framework/tools/tool-memory/) as well.

**Comment by vasinov** [comment]
@mgcollie, thanks for reporting those! We made several breaking changes in the last update and the docs for two tool activities (in `FileManager` and `TextProcessor`) weren't updated. I just pushed a docs update with fixed examples, so it should be all good now.

**Comment by mgcollie** [comment]
@vasinov my pleasure. glad to help. I can confirm that the new updated docs are working as expected.  thanks for the quick fix.
