### ISSUE TITLE
BedrockClaudePromptModelDriver results in ValidationError for Claude V3* models due to incorrect invoke struct

### ISSUE THREAD

**Issue by njedema** [griptape-ai/griptape#672]
- [ X] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
Invoking Claude V3 models on AWS Bedrock using the provided griptape drivers fails because the input structure Bedrock wants seems to be different for V3 models. Attempting to invoke any V3 model results in a botocore validation error that retries until the driver gives up.

**To Reproduce**
- Copy the demo script below and replace <YOUR PROFILE> with a sufficiently permissioned profile.
- Run it.
- Observe the errors that are logged.

```
"""
Use this file to verify that your griptape setup works with Bedrock LLMs
"""
import os
import boto3
from griptape.drivers import (
    AmazonBedrockPromptDriver,
    BedrockClaudePromptModelDriver
)
from griptape.structures import Agent

session = boto3.Session(region_name="us-west-2", profile_name=<YOUR PROFILE>)

#To verify this demo works, change `model` below to "anthropic.claude-v2"
prompt_driver = AmazonBedrockPromptDriver(
    model="anthropic.claude-3-sonnet-20240229-v1:0",
    prompt_model_driver=BedrockClaudePromptModelDriver(),
    session=session,
)

agent = Agent(prompt_driver=prompt_driver)

agent.run(
    "Write a haiku about academic research"
)
```

This script results in a retry-loop with the following error:
`WARNING:root:<RetryCallState 5948526160: attempt #10; slept for 66.0; last result: failed (ValidationException An error occurred (ValidationException) when calling the InvokeModel operation: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.)>`

**Expected behavior**
I expect BedrockClaudePromptModelDriver to handle input key switching based on the model version invoked. A clean solution would be to differentiate versions in the ModelDriver - e.g. BedrockClaudeLTEv2PromptModelDriver and BedrockClaudeGTEv3PromptModelDriver. 

**Desktop (please complete the following information)**:

OS: MacOS
Version: Ventura 13.6.4
griptape: 0.22.3
boto3: 1.34.11
botocore: 1.34.11

**Additional context**
This is an issue in Langchain and other frameworks as well and the root seems to be the Bedrock API input required for different model versions. See https://github.com/langchain-ai/langchain/issues/18513 for more. This thread is helpful in that it includes the AWS-approved request body that works for V3+ models:
```
{
  "max_tokens": 1024, 
  "system": "Today is January 1, 2024. Only respond in Haiku", 
  "messages": [{"role": "user", "content": "Hello, Claude"}], 
  "anthropic_version": "bedrock-2023-05-31"
}
```
I have not tested that this fix works; please verify.

**Comment by collindutter** [comment]
Closed by https://github.com/griptape-ai/griptape/pull/694
