### ISSUE TITLE
`LocalEmbeddingDriver`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#71]
Developers want to generate embeddings locally, so we need to build a driver for that.

Before starting on the issue, let's figure out what approach we should use (e.g., gensim).

**Comment by collindutter** [comment]
Closing, this can be accomplished with something like an [Ollama Embedding Driver](https://docs.griptape.ai/stable/griptape-framework/drivers/embedding-drivers/#ollama)
