### ISSUE TITLE
Azure OpenAI api version `2023-12-01-preview` deprecation

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#730]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 0.5.1]

**Additional context**

**Comment by derekpai** [comment]
retiring on July 1, 2024. Marking as Medium / XS.

**Comment by derekpai** [comment]
fix is here: https://github.com/griptape-ai/griptape/pull/731
