### ISSUE TITLE
Bing Search Wrapper for WebSearch tool

### ISSUE THREAD

**Issue by ccr-fan-3000** [griptape-ai/griptape#734]
Hello, 

I have been using the WebSearch tool and created a Google API key and Search ID as required. I would prefer to use Bing over Google moving forward and I wonder if this tool could be expanded to allow for a Bing Search Id and API Key.

**Comment by collindutter** [comment]
Hi @ccr-fan-3000, this functionality would likely come as part of https://github.com/griptape-ai/griptape/issues/383. I will update that issue to include Bing Search.
