### ISSUE TITLE
sentencepiece Tokenizer 

### ISSUE THREAD

**Issue by kyleroche** [griptape-ai/griptape#75]
**Describe the solution you'd like**
tokenizer for https://github.com/google/sentencepiece/blob/master/python/README.md

This would be used for Google Vertex AI Prompt driver

**Comment by derekpai** [comment]
Evaluate in a month

**Comment by collindutter** [comment]
Closing as we ended up integrating with [google generative AI](https://github.com/google-gemini/generative-ai-python) which provides a tokenizer.
