### ISSUE TITLE
Count Token Usage for Open AI

### ISSUE THREAD

**Issue by Jchang4** [griptape-ai/griptape#77]
**Is your feature request related to a problem? Please describe.**
I see a lot of back and forth when I run some of the examples, like where we're saving texts and blobs to, etc. 
So I wanted to compare token usage for similar tasks from Langchain and Griptape. 

**Describe the solution you'd like**
A way to count the number of tokens spent to fulfill a request. 

For example, let's say you have an agent that is doing multiple things, similar to the [RestApiClient Example](https://docs.griptape.ai/en/latest/griptape-tools/official-tools/rest-api-client/). I'd like to know how many tokens we use to fulfill this request to compare to other frameworks. 

**Describe alternatives you've considered**
I tried using Langchain's counter but it only works with Langchain LLMs. I also searched to see if the OpenAI package has this functionality already but it doesn't seem so. 

**Additional context**
N/A

**Comment by Jchang4** [comment]
Also want to say thank you for your work! Griptape seems like a much better bet than langchain, especially to avoid blowing context!

**Comment by vasinov** [comment]
@Jchang4, thanks for submitting the issue and for the kind words! :)

This is a super important issue and we are going to address it as soon as https://github.com/griptape-ai/griptape/issues/46 is complete. Will update you once it's done.

**Comment by Jchang4** [comment]
Oh also note, I checked the Open AI Usage dashboard and I do see quite a difference between langchain and griptape costs

**Comment by vasinov** [comment]
Which one uses fewer tokens in your experience? :) Also, our of curiosity, what were the two setups that you compared? (e.g., number of tools, rules, etc.)

**Comment by vasinov** [comment]
@Jchang4, we added support for counting tokens in Griptape! Check out this example: https://docs.griptape.ai/en/latest/examples/count-tokens/

**Comment by Jchang4** [comment]
![image](https://github.com/griptape-ai/griptape/assets/19507255/5b3fe907-a578-4a52-99d9-3a965c4bb8b6)
