### ISSUE TITLE
Add StructureRunDrivers to the documentation sidebar

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#773]
- [ x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
StructureRunDrivers documentation page is missing from the sidebar:
https://docs.griptape.ai/stable/griptape-framework/drivers/structure-run-drivers/

**Comment by collindutter** [comment]
https://github.com/griptape-ai/griptape/pull/776
