### ISSUE TITLE
`AwsRedshiftSqlDriver`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#85]
Customers need a way to allow LLMs to access their Redshift tables with IAM credentials.

I propose building the `AwsRedshiftSqlDriver` based on [RedshiftDataAPIService](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift-data.html).

**Comment by collindutter** [comment]
https://github.com/griptape-ai/griptape-labs/pull/3 might serve as a good starting point.
