### ISSUE TITLE
Handle `ErrorArtifact`s returned from tasks gracefully in a Pipeline/Workflow

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#863]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
Currently, if a task in the middle of a Pipeline or Workflow returns an `ErrorArtifact`, the entire Structure short-circuits and ends. This can lead to a situation where the `output_task` output is `None`. 

**Describe the solution you'd like**
I would expect more graceful handling of `ErrorArtifacts` returned from tasks. 
- a way to mark a Structure or individual Tasks as `fail_fast = True/False` to control this behavior.
- a way to "catch" `ErrorArtifacts` in a Pipeline or Workflow by specifying a Task that will be run only if an `ErrorArtifact` gets returned

**Describe alternatives you've considered**

**Additional context**
[Lines in `workflow.py` that cause this behavior](https://github.com/griptape-ai/griptape/blob/main/griptape/structures/workflow.py#L107-L110)
[Lines in `pipeline.py` that cause this behavior](https://github.com/griptape-ai/griptape/blob/main/griptape/structures/pipeline.py#L81-L82)

**Comment by michal-repo** [comment]
>     * a way to "catch" `ErrorArtifacts` in a Pipeline or Workflow by specifying a Task that will be run only if an `ErrorArtifact` gets returned


You should be able to instruct Agent that is using these Tools to run something if Tool returns error.

Just write such instruction in Rule, take a look at this example:
https://github.com/michal-repo/griptape-answer-cache-tool/blob/d7e4afbe1e8e96452b07db2c1d22cdc89dc9b23b/examples/example.py#L41

Agent is using specific method on Tool only if conditions are met.

**Comment by vachillo** [comment]
> > ```
> > * a way to "catch" `ErrorArtifacts` in a Pipeline or Workflow by specifying a Task that will be run only if an `ErrorArtifact` gets returned
> > ```
> 
> You should be able to instruct Agent that is using these Tools to run something if Tool returns error.
> 
> Just write such instruction in Rule, take a look at this example: https://github.com/michal-repo/griptape-answer-cache-tool/blob/d7e4afbe1e8e96452b07db2c1d22cdc89dc9b23b/examples/example.py#L41
> 
> Agent is using specific method on Tool only if conditions are met.

for an Agent, this works. however, pipelines and workflows are running `Tasks` directly and not passing the outputs back to the LLM. When I am constructing these two structures, I want full control over what the next step is if there is an error.

**Comment by collindutter** [comment]
@vachillo can this issue be closed with the introduction of `fail_fast`?

**Comment by vachillo** [comment]
> * a way to "catch" `ErrorArtifacts` in a Pipeline or Workflow by specifying a Task that will be run only if an `ErrorArtifact` gets returned

@collindutter i think this is still pending. I was working on a "branch task" to solve this, it never got over the finish line.

**Comment by collindutter** [comment]
@vachillo now that https://github.com/griptape-ai/griptape/pull/1404 is merged, can this be closed?
