### ISSUE TITLE
Allow/denylist activity parameters in addition to just methods

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#871]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
When allow/denylisting a method on a Schema that gets passed to the LLM, it would be nice to allow/deny method parameters as well. this would allow more fine-grained control over parameters that get set by the LLM vs the developer.

**Describe alternatives you've considered**

**Additional context**
would probably involve some more checks [in this method](https://github.com/griptape-ai/griptape/blob/dev/griptape/mixins/activity_mixin.py#L76-L84)

**Comment by collindutter** [comment]
I can envision the syntax of this looking something like:
```python
RestApiClient(
    denylist={
        "patch": ["path_params"]
    }
)
```
But then the Tool is required to handle missing values. I think https://github.com/griptape-ai/griptape/issues/306 needs to be implemented first.

**Comment by vachillo** [comment]
> I can envision the syntax of this looking something like:
> 
> ```python
> RestApiClient(
>     denylist={
>         "patch": ["path_params"]
>     }
> )
> ```
> 
> But then the Tool is required to handle missing values. I think #306 needs to be implemented first.

totally agree. i think during validation we could check if a parameter is being denied and check for some kind of default value? fail fast(er)

**Comment by collindutter** [comment]
Duplicate https://github.com/griptape-ai/griptape/issues/132
