### ISSUE TITLE
`Workflow.run()` will never return if a `Task` raises an uncaught exception

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#876]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 0.5.1]

**Additional context**

**Comment by collindutter** [comment]
@vachillo can you provide a reproducible example?

**Comment by collindutter** [comment]
@vachillo bump

**Comment by vachillo** [comment]
transient and hard to reproduce
