### ISSUE TITLE
Don't require passing `tasks` on `Workflow()` if using imperative syntax.

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#896]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
When using the imperative syntax to build a `Workflow`, you should not have to also explicitly list all tasks in the workflow as well. 

**Describe the solution you'd like**
For example (taken from the docs):
```
from griptape.tasks import PromptTask
from griptape.structures import Workflow
from griptape.rules import Rule

animal_task = PromptTask("Name an animal", id="animal")
adjective_task = PromptTask("Describe {{ parent_outputs['animal'] }} with an adjective", id="adjective")
new_animal_task = PromptTask("Name a {{ parent_outputs['adjective'] }} animal", id="new-animal")

adjective_task.add_parent(animal_task)
new_animal_task.add_parent(adjective_task)

workflow = Workflow(
    tasks=[animal_task, adjective_task, new_animal_task],
    rules=[Rule("output a single lowercase word")],
)

workflow.run()
```
the explicit passing of the list of tasks should not be required and instead it should be possible to do this:
```
from griptape.tasks import PromptTask
from griptape.structures import Workflow
from griptape.rules import Rule

workflow = Workflow( 
    rules=[Rule("output a single lowercase word")],
)

animal_task = PromptTask("Name an animal", id="animal")
adjective_task = PromptTask("Describe {{ parent_outputs['animal'] }} with an adjective", id="adjective")
new_animal_task = PromptTask("Name a {{ parent_outputs['adjective'] }} animal", id="new-animal")

workflow.add_task(animal_task)
adjective_task.add_parent(animal_task)
new_animal_task.add_parent(adjective_task)

workflow.run()
```
where the only task added to the workflow contains references to its other tasks, and the workflow should work out the DAG by itself.

**Describe alternatives you've considered**

**Additional context**

**Comment by shhlife** [comment]
I love this enhancement idea - it'll make things much more intuitive! :)

**Comment by collindutter** [comment]
I think this should be implemented via the following:
1. Change `BaseTask.parents/children` from a property to an `attrs` field.
2. Change `BaseTask.parent_ids/child_ids` from an `attrs` field to a property.
3. Change `BaseTask.add_parent/add_child` to only accept `task: BaseTask`. Add the Task to `BaseTask.parents/children`.
4. Add `Structure.resolve_tasks()` that recursively explores all children of the Tasks in `Structure.tasks`. If a child is not found in `Structure.tasks`, add it.

**Comment by vachillo** [comment]
focusing on improving documentation rather than changing the syntax.
