### ISSUE TITLE
Tools vs Functions

### ISSUE THREAD

**Issue by rcarmo** [griptape-ai/griptape#91]
**Is your feature request related to a problem? Please describe.**

I was wondering what the plans are for supporting [OpenAI function calling](https://platform.openai.com/docs/guides/gpt/function-calling) since that might help with LLM reliability and tool development.

**Describe the solution you'd like**
I would like to have `griptape` support OpenAI function calling internally and maintain the same semantics.

**Describe alternatives you've considered**
N/A

**Additional context**
I am evaluating `griptape` for my projects and have found that the function calling functionality makes for more reliable interactions with the 0613 series of models.

**Comment by vasinov** [comment]
@rcarmo, thanks for submitting the issue! As of today, we don't plan to support OpenAI function calling, as Griptape is framework-agnostic and we implement our own CoT and tool schema injection and validation logic.

I am curious though what types of queries/scenarios you are seeing OpenAI functions performing better at than Griptape tools. Are you in a position to share those? Would be interesting to measure and see if it's worth the effort to support functions via the prompt driver somehow.

**Comment by vasinov** [comment]
@rcarmo, just checking in to see if you could share comparison tests between function calling and Griptape tools. Also, wondering whether you've been running your tests with gpt-3 or gpt-4 (I know you mentioned 0613 but wondering which model specifically). Thanks!

**Comment by SAI-sentinal-ai** [comment]
Hello just following up on this. Is there an example of how Griptape tools can guarantee output as the 0613 models? e.g., given a product description, extract the height and width. This works very well with 0613, as I can always return product_width and product_height. How would I achieve this using Griptape? thanks!
