### ISSUE TITLE
Add `JsonArtifact`

### ISSUE THREAD

**Issue by vachillo** [griptape-ai/griptape#935]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
I want a way to pass around json-serialized values without having to explicitly de/serialize the dict myself

**Describe the solution you'd like**
`JsonArtifact` that takes a dict and serializes to json.

**Describe alternatives you've considered**

**Additional context**

**Comment by collindutter** [comment]
Related: https://github.com/griptape-ai/griptape/issues/439
