### ISSUE TITLE
Vector driver for MongoDB

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#94]
Developers are interested in using [MongoDB Atlas](https://www.mongodb.com/docs/atlas/getting-started/) as a vector store while using Griptape.

I propose building a `MongoDbAtlasVectorStoreDriver` that implements that functionality.

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like adding small features) by writing pull requests.
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)
