### ISSUE TITLE
Code Assist AI for devs building with Griptape

### ISSUE THREAD

**Issue by samyakkkk** [griptape-ai/griptape#997]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

Dear maintainers, greetings from [CommandDash](https://commanddash.io)! 

We are a tool to turn docs and examples of your library into a code generation AI agent which **helps devs directly generate code for your library as per their requirements.**

Our team came across Griptape Framework and figured it could be helpful for new developers building on it to have one such agent. It's ready and is accessible on: [Web](https://app.commanddash.io/agent?github=https://github.com/griptape-ai/griptape) (Try here!) | [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=WelltestedAI.fluttergpt) 

You can link this in your readme as a badge:

<a href="https://app.commanddash.io/agent?github=https://github.com/griptape-ai/griptape"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA?style=for-the-badge"></a>
```md
<a href="https://app.commanddash.io/agent?github=https://github.com/griptape-ai/griptape"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```
Please feel free to mention it if you believe this could be helpful for new users. Or, close the issue if not. 🙏🏻

_The agent is free to use, fully safe (no data retained) and auto-refreshes to stay upto date._

Best wishes!

**Comment by collindutter** [comment]
Hey @samyakkkk, thanks for sharing your tool! I'm going to close as we're not looking to introduce any more badges at this time. You are welcome to join our Discord to see if any Griptape developers are looking for a solution like this.
